/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/block.proto

package common

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	Header               *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 []byte       `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_120dc7a61108db55, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type BlockHeader struct {
	Number               uint64   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	ParentHash           []byte   `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BodyHash             []byte   `protobuf:"bytes,3,opt,name=body_hash,json=bodyHash,proto3" json:"body_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_120dc7a61108db55, []int{1}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *BlockHeader) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeader) GetBodyHash() []byte {
	if m != nil {
		return m.BodyHash
	}
	return nil
}

type BlockBody struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockBody) Reset()         { *m = BlockBody{} }
func (m *BlockBody) String() string { return proto.CompactTextString(m) }
func (*BlockBody) ProtoMessage()    {}
func (*BlockBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_120dc7a61108db55, []int{2}
}

func (m *BlockBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockBody.Unmarshal(m, b)
}
func (m *BlockBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockBody.Marshal(b, m, deterministic)
}
func (m *BlockBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockBody.Merge(m, src)
}
func (m *BlockBody) XXX_Size() int {
	return xxx_messageInfo_BlockBody.Size(m)
}
func (m *BlockBody) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockBody.DiscardUnknown(m)
}

var xxx_messageInfo_BlockBody proto.InternalMessageInfo

func (m *BlockBody) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockAndResult struct {
	Block                *Block       `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Result               *BlockResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BlockAndResult) Reset()         { *m = BlockAndResult{} }
func (m *BlockAndResult) String() string { return proto.CompactTextString(m) }
func (*BlockAndResult) ProtoMessage()    {}
func (*BlockAndResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_120dc7a61108db55, []int{3}
}

func (m *BlockAndResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockAndResult.Unmarshal(m, b)
}
func (m *BlockAndResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockAndResult.Marshal(b, m, deterministic)
}
func (m *BlockAndResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockAndResult.Merge(m, src)
}
func (m *BlockAndResult) XXX_Size() int {
	return xxx_messageInfo_BlockAndResult.Size(m)
}
func (m *BlockAndResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockAndResult.DiscardUnknown(m)
}

var xxx_messageInfo_BlockAndResult proto.InternalMessageInfo

func (m *BlockAndResult) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockAndResult) GetResult() *BlockResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "common.Block")
	proto.RegisterType((*BlockHeader)(nil), "common.BlockHeader")
	proto.RegisterType((*BlockBody)(nil), "common.BlockBody")
	proto.RegisterType((*BlockAndResult)(nil), "common.BlockAndResult")
}

func init() {
	proto.RegisterFile("common/block.proto", fileDescriptor_120dc7a61108db55)
}

var fileDescriptor_120dc7a61108db55 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xa9, 0xdb, 0x8a, 0x7b, 0x9b, 0x1e, 0x22, 0x48, 0xd1, 0x83, 0xa3, 0xbb, 0x0c, 0x84,
	0x16, 0x14, 0xf1, 0x6c, 0xf1, 0xd0, 0x73, 0xf0, 0x24, 0x82, 0xa4, 0x69, 0x30, 0xc1, 0x35, 0xaf,
	0x24, 0x29, 0x63, 0xff, 0xbd, 0x34, 0x89, 0xd8, 0x79, 0x6b, 0xde, 0xef, 0xfb, 0xbe, 0xbe, 0xf7,
	0x01, 0xe1, 0xd8, 0x75, 0xa8, 0xcb, 0x66, 0x8f, 0xfc, 0xbb, 0xe8, 0x0d, 0x3a, 0x24, 0x69, 0x98,
	0xdd, 0x64, 0x91, 0x39, 0xc3, 0xb4, 0x65, 0xdc, 0x29, 0xd4, 0x41, 0x91, 0xd7, 0xb0, 0xa8, 0x46,
	0x03, 0xb9, 0x87, 0x54, 0x0a, 0xd6, 0x0a, 0x93, 0x25, 0x9b, 0x64, 0xb7, 0x7a, 0xb8, 0x2a, 0x82,
	0xa7, 0xf0, 0xb8, 0xf6, 0x88, 0x46, 0x09, 0x21, 0x30, 0x6f, 0xb0, 0x3d, 0x66, 0x67, 0x9b, 0x64,
	0xb7, 0xa6, 0xfe, 0x3b, 0xe7, 0xb0, 0x9a, 0x48, 0xc9, 0x35, 0xa4, 0x7a, 0xe8, 0x9a, 0x98, 0x37,
	0xa7, 0xf1, 0x45, 0xee, 0x60, 0xd5, 0x33, 0x23, 0xb4, 0xfb, 0x94, 0xcc, 0xca, 0x98, 0x00, 0x61,
	0x54, 0x33, 0x2b, 0xc9, 0x2d, 0x2c, 0xc7, 0xbc, 0x80, 0x67, 0x1e, 0x9f, 0x8f, 0x83, 0x11, 0xe6,
	0xaf, 0xb0, 0xf4, 0x3f, 0xa9, 0xb0, 0x3d, 0x92, 0x67, 0x58, 0x4f, 0x0e, 0xb2, 0x59, 0xb2, 0x99,
	0x4d, 0x17, 0x7f, 0xfb, 0x63, 0xf4, 0x44, 0x98, 0x37, 0x70, 0xe9, 0x53, 0x5e, 0x74, 0x4b, 0x85,
	0x1d, 0xf6, 0x8e, 0x6c, 0x61, 0xe1, 0x7b, 0x8b, 0xc7, 0x5f, 0x9c, 0x1c, 0x4f, 0x03, 0x1b, 0x2b,
	0x32, 0x5e, 0xee, 0xb7, 0xfe, 0x5f, 0x51, 0x48, 0xa2, 0x51, 0x52, 0x7d, 0xc0, 0x96, 0x63, 0x57,
	0xc8, 0x81, 0x1d, 0x84, 0x2a, 0x0e, 0x4a, 0x68, 0x61, 0xb8, 0x64, 0x2a, 0x16, 0x1f, 0xad, 0xef,
	0x4f, 0x5f, 0xca, 0xfd, 0x8a, 0x38, 0x76, 0x65, 0x8f, 0xca, 0x5a, 0xd4, 0x56, 0x30, 0xc3, 0x65,
	0x39, 0xb1, 0x95, 0xde, 0x56, 0x06, 0x5b, 0x93, 0xfa, 0xd7, 0xe3, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa9, 0x45, 0xd9, 0xb1, 0xf5, 0x01, 0x00, 0x00,
}
