// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/chainconfig.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DBType int32

const (
	DBType_LEVELDB    DBType = 0
	DBType_MYSQL      DBType = 1
	DBType_POSTGRESQL DBType = 2
)

var DBType_name = map[int32]string{
	0: "LEVELDB",
	1: "MYSQL",
	2: "POSTGRESQL",
}

var DBType_value = map[string]int32{
	"LEVELDB":    0,
	"MYSQL":      1,
	"POSTGRESQL": 2,
}

func (x DBType) String() string {
	return proto.EnumName(DBType_name, int32(x))
}

func (DBType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6043edf3102f3790, []int{0}
}

// Chain config
type ChainConfig struct {
	ChainId              string          `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Organizations        []*Organization `protobuf:"bytes,2,rep,name=organizations,proto3" json:"organizations,omitempty"`
	Consensus            []byte          `protobuf:"bytes,3,opt,name=consensus,proto3" json:"consensus,omitempty"`
	DbType               DBType          `protobuf:"varint,4,opt,name=db_type,json=dbType,proto3,enum=common.DBType" json:"db_type,omitempty"`
	ConfigPolicy         string          `protobuf:"bytes,5,opt,name=configPolicy,proto3" json:"configPolicy,omitempty"`
	LifecyclePolicy      string          `protobuf:"bytes,6,opt,name=lifecyclePolicy,proto3" json:"lifecyclePolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChainConfig) Reset()         { *m = ChainConfig{} }
func (m *ChainConfig) String() string { return proto.CompactTextString(m) }
func (*ChainConfig) ProtoMessage()    {}
func (*ChainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6043edf3102f3790, []int{0}
}

func (m *ChainConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainConfig.Unmarshal(m, b)
}
func (m *ChainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainConfig.Marshal(b, m, deterministic)
}
func (m *ChainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainConfig.Merge(m, src)
}
func (m *ChainConfig) XXX_Size() int {
	return xxx_messageInfo_ChainConfig.Size(m)
}
func (m *ChainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ChainConfig proto.InternalMessageInfo

func (m *ChainConfig) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *ChainConfig) GetOrganizations() []*Organization {
	if m != nil {
		return m.Organizations
	}
	return nil
}

func (m *ChainConfig) GetConsensus() []byte {
	if m != nil {
		return m.Consensus
	}
	return nil
}

func (m *ChainConfig) GetDbType() DBType {
	if m != nil {
		return m.DbType
	}
	return DBType_LEVELDB
}

func (m *ChainConfig) GetConfigPolicy() string {
	if m != nil {
		return m.ConfigPolicy
	}
	return ""
}

func (m *ChainConfig) GetLifecyclePolicy() string {
	if m != nil {
		return m.LifecyclePolicy
	}
	return ""
}

type Organization struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RootCert             []byte   `protobuf:"bytes,2,opt,name=rootCert,proto3" json:"rootCert,omitempty"`
	AdminCert            []byte   `protobuf:"bytes,3,opt,name=adminCert,proto3" json:"adminCert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_6043edf3102f3790, []int{1}
}

func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (m *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(m, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetRootCert() []byte {
	if m != nil {
		return m.RootCert
	}
	return nil
}

func (m *Organization) GetAdminCert() []byte {
	if m != nil {
		return m.AdminCert
	}
	return nil
}

type ChainMeta struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	IsQuitting           bool     `protobuf:"varint,2,opt,name=isQuitting,proto3" json:"isQuitting,omitempty"`
	DbType               DBType   `protobuf:"varint,4,opt,name=db_type,json=dbType,proto3,enum=common.DBType" json:"db_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainMeta) Reset()         { *m = ChainMeta{} }
func (m *ChainMeta) String() string { return proto.CompactTextString(m) }
func (*ChainMeta) ProtoMessage()    {}
func (*ChainMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_6043edf3102f3790, []int{2}
}

func (m *ChainMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainMeta.Unmarshal(m, b)
}
func (m *ChainMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainMeta.Marshal(b, m, deterministic)
}
func (m *ChainMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainMeta.Merge(m, src)
}
func (m *ChainMeta) XXX_Size() int {
	return xxx_messageInfo_ChainMeta.Size(m)
}
func (m *ChainMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ChainMeta proto.InternalMessageInfo

func (m *ChainMeta) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *ChainMeta) GetIsQuitting() bool {
	if m != nil {
		return m.IsQuitting
	}
	return false
}

func (m *ChainMeta) GetDbType() DBType {
	if m != nil {
		return m.DbType
	}
	return DBType_LEVELDB
}

func init() {
	proto.RegisterEnum("common.DBType", DBType_name, DBType_value)
	proto.RegisterType((*ChainConfig)(nil), "common.ChainConfig")
	proto.RegisterType((*Organization)(nil), "common.Organization")
	proto.RegisterType((*ChainMeta)(nil), "common.ChainMeta")
}

func init() {
	proto.RegisterFile("common/chainconfig.proto", fileDescriptor_6043edf3102f3790)
}

var fileDescriptor_6043edf3102f3790 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x8b, 0xda, 0x40,
	0x18, 0x6e, 0xfc, 0x88, 0xe6, 0xd5, 0x5a, 0x19, 0x7a, 0x48, 0x4b, 0x29, 0x21, 0x3d, 0x34, 0xf4,
	0x90, 0x14, 0x4b, 0x2f, 0x3d, 0xfa, 0x41, 0x29, 0x28, 0x6a, 0x94, 0xc2, 0x2e, 0x82, 0x8c, 0x93,
	0x31, 0x0e, 0x98, 0x99, 0x90, 0x8c, 0x48, 0xf6, 0x9f, 0xef, 0x6d, 0xc9, 0x24, 0xba, 0x71, 0x0f,
	0xcb, 0x9e, 0x92, 0xe7, 0xe3, 0x9d, 0x79, 0x9e, 0x37, 0x01, 0x93, 0x88, 0x28, 0x12, 0xdc, 0x23,
	0x07, 0xcc, 0x38, 0x11, 0x7c, 0xcf, 0x42, 0x37, 0x4e, 0x84, 0x14, 0x48, 0x2f, 0x14, 0xfb, 0x51,
	0x83, 0xce, 0x28, 0x57, 0x47, 0x4a, 0x45, 0x9f, 0xa0, 0xad, 0xcc, 0x5b, 0x16, 0x98, 0x9a, 0xa5,
	0x39, 0x86, 0xdf, 0x52, 0xf8, 0x5f, 0x80, 0xfe, 0xc0, 0x7b, 0x91, 0x84, 0x98, 0xb3, 0x07, 0x2c,
	0x99, 0xe0, 0xa9, 0x59, 0xb3, 0xea, 0x4e, 0x67, 0xf0, 0xd1, 0x2d, 0x8e, 0x72, 0xe7, 0x15, 0xd1,
	0xbf, 0xb5, 0xa2, 0x2f, 0x60, 0x10, 0xc1, 0x53, 0xca, 0xd3, 0x53, 0x6a, 0xd6, 0x2d, 0xcd, 0xe9,
	0xfa, 0xcf, 0x04, 0xfa, 0x0e, 0xad, 0x60, 0xb7, 0x95, 0x59, 0x4c, 0xcd, 0x86, 0xa5, 0x39, 0xbd,
	0x41, 0xef, 0x72, 0xe6, 0x78, 0xb8, 0xce, 0x62, 0xea, 0xeb, 0xc1, 0x2e, 0x7f, 0x22, 0x1b, 0xba,
	0x45, 0x8b, 0x85, 0x38, 0x32, 0x92, 0x99, 0x4d, 0x95, 0xf0, 0x86, 0x43, 0x0e, 0x7c, 0x38, 0xb2,
	0x3d, 0x25, 0x19, 0x39, 0xd2, 0xd2, 0xa6, 0x2b, 0xdb, 0x4b, 0xda, 0xde, 0x40, 0xb7, 0x9a, 0x19,
	0x21, 0x68, 0x70, 0x1c, 0xd1, 0xb2, 0xb7, 0x7a, 0x47, 0x9f, 0xa1, 0x9d, 0x08, 0x21, 0x47, 0x34,
	0x91, 0x66, 0x4d, 0xe5, 0xbe, 0xe2, 0xbc, 0x14, 0x0e, 0x22, 0xc6, 0x95, 0x58, 0x96, 0xba, 0x12,
	0xb6, 0x00, 0x43, 0x2d, 0x76, 0x46, 0x25, 0x7e, 0x6d, 0xad, 0x5f, 0x01, 0x58, 0xba, 0x3c, 0x31,
	0x29, 0x19, 0x0f, 0xd5, 0x1d, 0x6d, 0xbf, 0xc2, 0xbc, 0x79, 0x39, 0x3f, 0x7e, 0x82, 0x5e, 0x30,
	0xa8, 0x03, 0xad, 0xe9, 0xe4, 0xff, 0x64, 0x3a, 0x1e, 0xf6, 0xdf, 0x21, 0x03, 0x9a, 0xb3, 0xbb,
	0xd5, 0x72, 0xda, 0xd7, 0x50, 0x0f, 0x60, 0x31, 0x5f, 0xad, 0xff, 0xfa, 0x93, 0x1c, 0xd7, 0x86,
	0x1b, 0xf8, 0x46, 0x44, 0xe4, 0x1e, 0x4e, 0xf8, 0x4c, 0x99, 0x7b, 0x66, 0x94, 0xd3, 0x44, 0xc5,
	0x2a, 0x7e, 0x92, 0xf2, 0x9e, 0xfb, 0xdf, 0x21, 0x93, 0x17, 0x13, 0x11, 0x91, 0x17, 0x0b, 0x96,
	0xa6, 0xf9, 0xc7, 0xc3, 0x09, 0x39, 0x78, 0x95, 0x31, 0x4f, 0x8d, 0x79, 0xc5, 0xd8, 0x4e, 0x57,
	0xe8, 0xd7, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0x23, 0xbd, 0x20, 0xfe, 0x85, 0x02, 0x00, 0x00,
}
