// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/ledger.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StateUpdates struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Types that are valid to be assigned to Updates:
	//	*StateUpdates_KvUpdates
	//	*StateUpdates_SqlUpdates
	Updates              isStateUpdates_Updates `protobuf_oneof:"updates"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StateUpdates) Reset()         { *m = StateUpdates{} }
func (m *StateUpdates) String() string { return proto.CompactTextString(m) }
func (*StateUpdates) ProtoMessage()    {}
func (*StateUpdates) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{0}
}

func (m *StateUpdates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateUpdates.Unmarshal(m, b)
}
func (m *StateUpdates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateUpdates.Marshal(b, m, deterministic)
}
func (m *StateUpdates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateUpdates.Merge(m, src)
}
func (m *StateUpdates) XXX_Size() int {
	return xxx_messageInfo_StateUpdates.Size(m)
}
func (m *StateUpdates) XXX_DiscardUnknown() {
	xxx_messageInfo_StateUpdates.DiscardUnknown(m)
}

var xxx_messageInfo_StateUpdates proto.InternalMessageInfo

func (m *StateUpdates) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type isStateUpdates_Updates interface {
	isStateUpdates_Updates()
}

type StateUpdates_KvUpdates struct {
	KvUpdates *KvStateUpdates `protobuf:"bytes,2,opt,name=kvUpdates,proto3,oneof"`
}

type StateUpdates_SqlUpdates struct {
	SqlUpdates *SqlStateUpdates `protobuf:"bytes,3,opt,name=sqlUpdates,proto3,oneof"`
}

func (*StateUpdates_KvUpdates) isStateUpdates_Updates() {}

func (*StateUpdates_SqlUpdates) isStateUpdates_Updates() {}

func (m *StateUpdates) GetUpdates() isStateUpdates_Updates {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *StateUpdates) GetKvUpdates() *KvStateUpdates {
	if x, ok := m.GetUpdates().(*StateUpdates_KvUpdates); ok {
		return x.KvUpdates
	}
	return nil
}

func (m *StateUpdates) GetSqlUpdates() *SqlStateUpdates {
	if x, ok := m.GetUpdates().(*StateUpdates_SqlUpdates); ok {
		return x.SqlUpdates
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StateUpdates) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StateUpdates_KvUpdates)(nil),
		(*StateUpdates_SqlUpdates)(nil),
	}
}

type KvStateUpdates struct {
	KeyVersions          []*KeyVersion    `protobuf:"bytes,1,rep,name=key_versions,json=keyVersions,proto3" json:"key_versions,omitempty"`
	ItrInfos             []*IterationInfo `protobuf:"bytes,2,rep,name=itr_infos,json=itrInfos,proto3" json:"itr_infos,omitempty"`
	Updates              []*KeyValue      `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty"`
	Deletes              []string         `protobuf:"bytes,4,rep,name=deletes,proto3" json:"deletes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *KvStateUpdates) Reset()         { *m = KvStateUpdates{} }
func (m *KvStateUpdates) String() string { return proto.CompactTextString(m) }
func (*KvStateUpdates) ProtoMessage()    {}
func (*KvStateUpdates) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{1}
}

func (m *KvStateUpdates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvStateUpdates.Unmarshal(m, b)
}
func (m *KvStateUpdates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvStateUpdates.Marshal(b, m, deterministic)
}
func (m *KvStateUpdates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvStateUpdates.Merge(m, src)
}
func (m *KvStateUpdates) XXX_Size() int {
	return xxx_messageInfo_KvStateUpdates.Size(m)
}
func (m *KvStateUpdates) XXX_DiscardUnknown() {
	xxx_messageInfo_KvStateUpdates.DiscardUnknown(m)
}

var xxx_messageInfo_KvStateUpdates proto.InternalMessageInfo

func (m *KvStateUpdates) GetKeyVersions() []*KeyVersion {
	if m != nil {
		return m.KeyVersions
	}
	return nil
}

func (m *KvStateUpdates) GetItrInfos() []*IterationInfo {
	if m != nil {
		return m.ItrInfos
	}
	return nil
}

func (m *KvStateUpdates) GetUpdates() []*KeyValue {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *KvStateUpdates) GetDeletes() []string {
	if m != nil {
		return m.Deletes
	}
	return nil
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{2}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KeyValue) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type KeyVersion struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version              *Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyVersion) Reset()         { *m = KeyVersion{} }
func (m *KeyVersion) String() string { return proto.CompactTextString(m) }
func (*KeyVersion) ProtoMessage()    {}
func (*KeyVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{3}
}

func (m *KeyVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyVersion.Unmarshal(m, b)
}
func (m *KeyVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyVersion.Marshal(b, m, deterministic)
}
func (m *KeyVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyVersion.Merge(m, src)
}
func (m *KeyVersion) XXX_Size() int {
	return xxx_messageInfo_KeyVersion.Size(m)
}
func (m *KeyVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyVersion.DiscardUnknown(m)
}

var xxx_messageInfo_KeyVersion proto.InternalMessageInfo

func (m *KeyVersion) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyVersion) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type ValueVersion struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version              *Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueVersion) Reset()         { *m = ValueVersion{} }
func (m *ValueVersion) String() string { return proto.CompactTextString(m) }
func (*ValueVersion) ProtoMessage()    {}
func (*ValueVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{4}
}

func (m *ValueVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueVersion.Unmarshal(m, b)
}
func (m *ValueVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueVersion.Marshal(b, m, deterministic)
}
func (m *ValueVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueVersion.Merge(m, src)
}
func (m *ValueVersion) XXX_Size() int {
	return xxx_messageInfo_ValueVersion.Size(m)
}
func (m *ValueVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ValueVersion proto.InternalMessageInfo

func (m *ValueVersion) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ValueVersion) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ValueVersion) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Version struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	TxNum                int32    `protobuf:"varint,2,opt,name=tx_num,json=txNum,proto3" json:"tx_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{5}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *Version) GetTxNum() int32 {
	if m != nil {
		return m.TxNum
	}
	return 0
}

type IterationInfo struct {
	StartKey             string      `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey               string      `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Inclusive            bool        `protobuf:"varint,3,opt,name=inclusive,proto3" json:"inclusive,omitempty"`
	Tree                 *MerkleTree `protobuf:"bytes,4,opt,name=tree,proto3" json:"tree,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IterationInfo) Reset()         { *m = IterationInfo{} }
func (m *IterationInfo) String() string { return proto.CompactTextString(m) }
func (*IterationInfo) ProtoMessage()    {}
func (*IterationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{6}
}

func (m *IterationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IterationInfo.Unmarshal(m, b)
}
func (m *IterationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IterationInfo.Marshal(b, m, deterministic)
}
func (m *IterationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IterationInfo.Merge(m, src)
}
func (m *IterationInfo) XXX_Size() int {
	return xxx_messageInfo_IterationInfo.Size(m)
}
func (m *IterationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IterationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IterationInfo proto.InternalMessageInfo

func (m *IterationInfo) GetStartKey() string {
	if m != nil {
		return m.StartKey
	}
	return ""
}

func (m *IterationInfo) GetEndKey() string {
	if m != nil {
		return m.EndKey
	}
	return ""
}

func (m *IterationInfo) GetInclusive() bool {
	if m != nil {
		return m.Inclusive
	}
	return false
}

func (m *IterationInfo) GetTree() *MerkleTree {
	if m != nil {
		return m.Tree
	}
	return nil
}

type MerkleTree struct {
	Level                int32    `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Nodes                [][]byte `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerkleTree) Reset()         { *m = MerkleTree{} }
func (m *MerkleTree) String() string { return proto.CompactTextString(m) }
func (*MerkleTree) ProtoMessage()    {}
func (*MerkleTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{7}
}

func (m *MerkleTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerkleTree.Unmarshal(m, b)
}
func (m *MerkleTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerkleTree.Marshal(b, m, deterministic)
}
func (m *MerkleTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerkleTree.Merge(m, src)
}
func (m *MerkleTree) XXX_Size() int {
	return xxx_messageInfo_MerkleTree.Size(m)
}
func (m *MerkleTree) XXX_DiscardUnknown() {
	xxx_messageInfo_MerkleTree.DiscardUnknown(m)
}

var xxx_messageInfo_MerkleTree proto.InternalMessageInfo

func (m *MerkleTree) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *MerkleTree) GetNodes() [][]byte {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type BlockPointer struct {
	FileNum              int32    `protobuf:"varint,1,opt,name=file_num,json=fileNum,proto3" json:"file_num,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockPointer) Reset()         { *m = BlockPointer{} }
func (m *BlockPointer) String() string { return proto.CompactTextString(m) }
func (*BlockPointer) ProtoMessage()    {}
func (*BlockPointer) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{8}
}

func (m *BlockPointer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockPointer.Unmarshal(m, b)
}
func (m *BlockPointer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockPointer.Marshal(b, m, deterministic)
}
func (m *BlockPointer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockPointer.Merge(m, src)
}
func (m *BlockPointer) XXX_Size() int {
	return xxx_messageInfo_BlockPointer.Size(m)
}
func (m *BlockPointer) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockPointer.DiscardUnknown(m)
}

var xxx_messageInfo_BlockPointer proto.InternalMessageInfo

func (m *BlockPointer) GetFileNum() int32 {
	if m != nil {
		return m.FileNum
	}
	return 0
}

func (m *BlockPointer) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SqlStateUpdates struct {
	SelectStmts          []*SelectStatement `protobuf:"bytes,1,rep,name=select_stmts,json=selectStmts,proto3" json:"select_stmts,omitempty"`
	InsertStmts          []*InsertStatement `protobuf:"bytes,2,rep,name=insert_stmts,json=insertStmts,proto3" json:"insert_stmts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SqlStateUpdates) Reset()         { *m = SqlStateUpdates{} }
func (m *SqlStateUpdates) String() string { return proto.CompactTextString(m) }
func (*SqlStateUpdates) ProtoMessage()    {}
func (*SqlStateUpdates) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{9}
}

func (m *SqlStateUpdates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlStateUpdates.Unmarshal(m, b)
}
func (m *SqlStateUpdates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlStateUpdates.Marshal(b, m, deterministic)
}
func (m *SqlStateUpdates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlStateUpdates.Merge(m, src)
}
func (m *SqlStateUpdates) XXX_Size() int {
	return xxx_messageInfo_SqlStateUpdates.Size(m)
}
func (m *SqlStateUpdates) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlStateUpdates.DiscardUnknown(m)
}

var xxx_messageInfo_SqlStateUpdates proto.InternalMessageInfo

func (m *SqlStateUpdates) GetSelectStmts() []*SelectStatement {
	if m != nil {
		return m.SelectStmts
	}
	return nil
}

func (m *SqlStateUpdates) GetInsertStmts() []*InsertStatement {
	if m != nil {
		return m.InsertStmts
	}
	return nil
}

// if numOfRows is 0, it means all rows of the select statement.
type SelectStatement struct {
	Query                string           `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Args                 *PrimitiveValues `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Tree                 *MerkleTree      `protobuf:"bytes,3,opt,name=tree,proto3" json:"tree,omitempty"`
	NumOfRows            uint64           `protobuf:"varint,4,opt,name=numOfRows,proto3" json:"numOfRows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SelectStatement) Reset()         { *m = SelectStatement{} }
func (m *SelectStatement) String() string { return proto.CompactTextString(m) }
func (*SelectStatement) ProtoMessage()    {}
func (*SelectStatement) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{10}
}

func (m *SelectStatement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectStatement.Unmarshal(m, b)
}
func (m *SelectStatement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectStatement.Marshal(b, m, deterministic)
}
func (m *SelectStatement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectStatement.Merge(m, src)
}
func (m *SelectStatement) XXX_Size() int {
	return xxx_messageInfo_SelectStatement.Size(m)
}
func (m *SelectStatement) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectStatement.DiscardUnknown(m)
}

var xxx_messageInfo_SelectStatement proto.InternalMessageInfo

func (m *SelectStatement) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SelectStatement) GetArgs() *PrimitiveValues {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *SelectStatement) GetTree() *MerkleTree {
	if m != nil {
		return m.Tree
	}
	return nil
}

func (m *SelectStatement) GetNumOfRows() uint64 {
	if m != nil {
		return m.NumOfRows
	}
	return 0
}

type InsertStatement struct {
	TableName string   `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Columns   []string `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// Types that are valid to be assigned to Values:
	//	*InsertStatement_InsertValues
	//	*InsertStatement_SelectRows
	Values               isInsertStatement_Values `protobuf_oneof:"values"`
	IsDelete             bool                     `protobuf:"varint,5,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *InsertStatement) Reset()         { *m = InsertStatement{} }
func (m *InsertStatement) String() string { return proto.CompactTextString(m) }
func (*InsertStatement) ProtoMessage()    {}
func (*InsertStatement) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{11}
}

func (m *InsertStatement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertStatement.Unmarshal(m, b)
}
func (m *InsertStatement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertStatement.Marshal(b, m, deterministic)
}
func (m *InsertStatement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertStatement.Merge(m, src)
}
func (m *InsertStatement) XXX_Size() int {
	return xxx_messageInfo_InsertStatement.Size(m)
}
func (m *InsertStatement) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertStatement.DiscardUnknown(m)
}

var xxx_messageInfo_InsertStatement proto.InternalMessageInfo

func (m *InsertStatement) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *InsertStatement) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

type isInsertStatement_Values interface {
	isInsertStatement_Values()
}

type InsertStatement_InsertValues struct {
	InsertValues *InsertValues `protobuf:"bytes,3,opt,name=insert_values,json=insertValues,proto3,oneof"`
}

type InsertStatement_SelectRows struct {
	SelectRows *SelectStatement `protobuf:"bytes,4,opt,name=select_rows,json=selectRows,proto3,oneof"`
}

func (*InsertStatement_InsertValues) isInsertStatement_Values() {}

func (*InsertStatement_SelectRows) isInsertStatement_Values() {}

func (m *InsertStatement) GetValues() isInsertStatement_Values {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *InsertStatement) GetInsertValues() *InsertValues {
	if x, ok := m.GetValues().(*InsertStatement_InsertValues); ok {
		return x.InsertValues
	}
	return nil
}

func (m *InsertStatement) GetSelectRows() *SelectStatement {
	if x, ok := m.GetValues().(*InsertStatement_SelectRows); ok {
		return x.SelectRows
	}
	return nil
}

func (m *InsertStatement) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*InsertStatement) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*InsertStatement_InsertValues)(nil),
		(*InsertStatement_SelectRows)(nil),
	}
}

type InsertValues struct {
	ValueTuples          []*ValueTuple `protobuf:"bytes,1,rep,name=valueTuples,proto3" json:"valueTuples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InsertValues) Reset()         { *m = InsertValues{} }
func (m *InsertValues) String() string { return proto.CompactTextString(m) }
func (*InsertValues) ProtoMessage()    {}
func (*InsertValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{12}
}

func (m *InsertValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertValues.Unmarshal(m, b)
}
func (m *InsertValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertValues.Marshal(b, m, deterministic)
}
func (m *InsertValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertValues.Merge(m, src)
}
func (m *InsertValues) XXX_Size() int {
	return xxx_messageInfo_InsertValues.Size(m)
}
func (m *InsertValues) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertValues.DiscardUnknown(m)
}

var xxx_messageInfo_InsertValues proto.InternalMessageInfo

func (m *InsertValues) GetValueTuples() []*ValueTuple {
	if m != nil {
		return m.ValueTuples
	}
	return nil
}

type ValueTuple struct {
	ValueExprs           []*ValueExpr `protobuf:"bytes,1,rep,name=valueExprs,proto3" json:"valueExprs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ValueTuple) Reset()         { *m = ValueTuple{} }
func (m *ValueTuple) String() string { return proto.CompactTextString(m) }
func (*ValueTuple) ProtoMessage()    {}
func (*ValueTuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{13}
}

func (m *ValueTuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueTuple.Unmarshal(m, b)
}
func (m *ValueTuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueTuple.Marshal(b, m, deterministic)
}
func (m *ValueTuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueTuple.Merge(m, src)
}
func (m *ValueTuple) XXX_Size() int {
	return xxx_messageInfo_ValueTuple.Size(m)
}
func (m *ValueTuple) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueTuple.DiscardUnknown(m)
}

var xxx_messageInfo_ValueTuple proto.InternalMessageInfo

func (m *ValueTuple) GetValueExprs() []*ValueExpr {
	if m != nil {
		return m.ValueExprs
	}
	return nil
}

type ValueExpr struct {
	Expr                 string           `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Args                 *PrimitiveValues `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ValueExpr) Reset()         { *m = ValueExpr{} }
func (m *ValueExpr) String() string { return proto.CompactTextString(m) }
func (*ValueExpr) ProtoMessage()    {}
func (*ValueExpr) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{14}
}

func (m *ValueExpr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueExpr.Unmarshal(m, b)
}
func (m *ValueExpr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueExpr.Marshal(b, m, deterministic)
}
func (m *ValueExpr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueExpr.Merge(m, src)
}
func (m *ValueExpr) XXX_Size() int {
	return xxx_messageInfo_ValueExpr.Size(m)
}
func (m *ValueExpr) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueExpr.DiscardUnknown(m)
}

var xxx_messageInfo_ValueExpr proto.InternalMessageInfo

func (m *ValueExpr) GetExpr() string {
	if m != nil {
		return m.Expr
	}
	return ""
}

func (m *ValueExpr) GetArgs() *PrimitiveValues {
	if m != nil {
		return m.Args
	}
	return nil
}

type PrimitiveValues struct {
	Values               []*PrimitiveValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PrimitiveValues) Reset()         { *m = PrimitiveValues{} }
func (m *PrimitiveValues) String() string { return proto.CompactTextString(m) }
func (*PrimitiveValues) ProtoMessage()    {}
func (*PrimitiveValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{15}
}

func (m *PrimitiveValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveValues.Unmarshal(m, b)
}
func (m *PrimitiveValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveValues.Marshal(b, m, deterministic)
}
func (m *PrimitiveValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveValues.Merge(m, src)
}
func (m *PrimitiveValues) XXX_Size() int {
	return xxx_messageInfo_PrimitiveValues.Size(m)
}
func (m *PrimitiveValues) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveValues.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveValues proto.InternalMessageInfo

func (m *PrimitiveValues) GetValues() []*PrimitiveValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type PrimitiveValue struct {
	// Types that are valid to be assigned to Value:
	//	*PrimitiveValue_DoubleValue
	//	*PrimitiveValue_FloatValue
	//	*PrimitiveValue_Int32Value
	//	*PrimitiveValue_Int64Value
	//	*PrimitiveValue_Uint32Value
	//	*PrimitiveValue_Uint64Value
	//	*PrimitiveValue_BoolValue
	//	*PrimitiveValue_StringValue
	//	*PrimitiveValue_BytesValue
	//	*PrimitiveValue_TimeValue
	Value                isPrimitiveValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PrimitiveValue) Reset()         { *m = PrimitiveValue{} }
func (m *PrimitiveValue) String() string { return proto.CompactTextString(m) }
func (*PrimitiveValue) ProtoMessage()    {}
func (*PrimitiveValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3410306adbea27, []int{16}
}

func (m *PrimitiveValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveValue.Unmarshal(m, b)
}
func (m *PrimitiveValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveValue.Marshal(b, m, deterministic)
}
func (m *PrimitiveValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveValue.Merge(m, src)
}
func (m *PrimitiveValue) XXX_Size() int {
	return xxx_messageInfo_PrimitiveValue.Size(m)
}
func (m *PrimitiveValue) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveValue.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveValue proto.InternalMessageInfo

type isPrimitiveValue_Value interface {
	isPrimitiveValue_Value()
}

type PrimitiveValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,1,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type PrimitiveValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,2,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type PrimitiveValue_Int32Value struct {
	Int32Value int32 `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type PrimitiveValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,4,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type PrimitiveValue_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,5,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type PrimitiveValue_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type PrimitiveValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,7,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type PrimitiveValue_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type PrimitiveValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type PrimitiveValue_TimeValue struct {
	TimeValue *timestamp.Timestamp `protobuf:"bytes,10,opt,name=time_value,json=timeValue,proto3,oneof"`
}

func (*PrimitiveValue_DoubleValue) isPrimitiveValue_Value() {}

func (*PrimitiveValue_FloatValue) isPrimitiveValue_Value() {}

func (*PrimitiveValue_Int32Value) isPrimitiveValue_Value() {}

func (*PrimitiveValue_Int64Value) isPrimitiveValue_Value() {}

func (*PrimitiveValue_Uint32Value) isPrimitiveValue_Value() {}

func (*PrimitiveValue_Uint64Value) isPrimitiveValue_Value() {}

func (*PrimitiveValue_BoolValue) isPrimitiveValue_Value() {}

func (*PrimitiveValue_StringValue) isPrimitiveValue_Value() {}

func (*PrimitiveValue_BytesValue) isPrimitiveValue_Value() {}

func (*PrimitiveValue_TimeValue) isPrimitiveValue_Value() {}

func (m *PrimitiveValue) GetValue() isPrimitiveValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PrimitiveValue) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*PrimitiveValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *PrimitiveValue) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*PrimitiveValue_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *PrimitiveValue) GetInt32Value() int32 {
	if x, ok := m.GetValue().(*PrimitiveValue_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *PrimitiveValue) GetInt64Value() int64 {
	if x, ok := m.GetValue().(*PrimitiveValue_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *PrimitiveValue) GetUint32Value() uint32 {
	if x, ok := m.GetValue().(*PrimitiveValue_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (m *PrimitiveValue) GetUint64Value() uint64 {
	if x, ok := m.GetValue().(*PrimitiveValue_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (m *PrimitiveValue) GetBoolValue() bool {
	if x, ok := m.GetValue().(*PrimitiveValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *PrimitiveValue) GetStringValue() string {
	if x, ok := m.GetValue().(*PrimitiveValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *PrimitiveValue) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*PrimitiveValue_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *PrimitiveValue) GetTimeValue() *timestamp.Timestamp {
	if x, ok := m.GetValue().(*PrimitiveValue_TimeValue); ok {
		return x.TimeValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PrimitiveValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PrimitiveValue_DoubleValue)(nil),
		(*PrimitiveValue_FloatValue)(nil),
		(*PrimitiveValue_Int32Value)(nil),
		(*PrimitiveValue_Int64Value)(nil),
		(*PrimitiveValue_Uint32Value)(nil),
		(*PrimitiveValue_Uint64Value)(nil),
		(*PrimitiveValue_BoolValue)(nil),
		(*PrimitiveValue_StringValue)(nil),
		(*PrimitiveValue_BytesValue)(nil),
		(*PrimitiveValue_TimeValue)(nil),
	}
}

func init() {
	proto.RegisterType((*StateUpdates)(nil), "common.StateUpdates")
	proto.RegisterType((*KvStateUpdates)(nil), "common.KvStateUpdates")
	proto.RegisterType((*KeyValue)(nil), "common.KeyValue")
	proto.RegisterType((*KeyVersion)(nil), "common.KeyVersion")
	proto.RegisterType((*ValueVersion)(nil), "common.ValueVersion")
	proto.RegisterType((*Version)(nil), "common.Version")
	proto.RegisterType((*IterationInfo)(nil), "common.IterationInfo")
	proto.RegisterType((*MerkleTree)(nil), "common.MerkleTree")
	proto.RegisterType((*BlockPointer)(nil), "common.BlockPointer")
	proto.RegisterType((*SqlStateUpdates)(nil), "common.SqlStateUpdates")
	proto.RegisterType((*SelectStatement)(nil), "common.SelectStatement")
	proto.RegisterType((*InsertStatement)(nil), "common.InsertStatement")
	proto.RegisterType((*InsertValues)(nil), "common.InsertValues")
	proto.RegisterType((*ValueTuple)(nil), "common.ValueTuple")
	proto.RegisterType((*ValueExpr)(nil), "common.ValueExpr")
	proto.RegisterType((*PrimitiveValues)(nil), "common.PrimitiveValues")
	proto.RegisterType((*PrimitiveValue)(nil), "common.PrimitiveValue")
}

func init() {
	proto.RegisterFile("common/ledger.proto", fileDescriptor_da3410306adbea27)
}

var fileDescriptor_da3410306adbea27 = []byte{
	// 1034 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xfd, 0x6e, 0x1b, 0x45,
	0x10, 0xcf, 0xc5, 0x9f, 0x37, 0x76, 0x9a, 0xb2, 0xb4, 0xa9, 0x09, 0x45, 0x0d, 0x57, 0x09, 0x05,
	0x90, 0x6c, 0x91, 0xa6, 0x11, 0xb4, 0x42, 0xa8, 0x51, 0x91, 0x12, 0x15, 0x42, 0xb4, 0x0d, 0xfd,
	0x03, 0x21, 0x59, 0x67, 0x7b, 0xec, 0xac, 0x7c, 0x77, 0xeb, 0xec, 0xee, 0x39, 0xf1, 0x23, 0x20,
	0x1e, 0x00, 0x89, 0x47, 0xe0, 0x2d, 0x78, 0x1c, 0xde, 0x02, 0xed, 0xd7, 0xdd, 0x39, 0x94, 0xaf,
	0xff, 0x6e, 0x7e, 0xf3, 0x9b, 0xd9, 0xdf, 0xce, 0xec, 0xce, 0x2d, 0xbc, 0x3b, 0xe6, 0x69, 0xca,
	0xb3, 0x41, 0x82, 0x93, 0x19, 0x8a, 0xfe, 0x42, 0x70, 0xc5, 0x49, 0xd3, 0x82, 0xbb, 0x8f, 0x66,
	0x9c, 0xcf, 0x12, 0x1c, 0x18, 0x74, 0x94, 0x4f, 0x07, 0x8a, 0xa5, 0x28, 0x55, 0x9c, 0x2e, 0x2c,
	0x31, 0xfa, 0x2d, 0x80, 0xee, 0x6b, 0x15, 0x2b, 0xfc, 0x7e, 0x31, 0x89, 0x15, 0x4a, 0xf2, 0x10,
	0xc2, 0x2c, 0x4e, 0x51, 0x2e, 0xe2, 0x31, 0xf6, 0x82, 0xbd, 0x60, 0x3f, 0xa4, 0x25, 0x40, 0x8e,
	0x20, 0x9c, 0x2f, 0x1d, 0xb5, 0xb7, 0xb9, 0x17, 0xec, 0x77, 0x0e, 0x76, 0xfa, 0x76, 0xad, 0xfe,
	0xab, 0x65, 0x35, 0xd1, 0xc9, 0x06, 0x2d, 0xa9, 0xe4, 0x0b, 0x00, 0x79, 0x95, 0xf8, 0xc0, 0x9a,
	0x09, 0x7c, 0xe0, 0x03, 0x5f, 0x5f, 0x25, 0xb7, 0x22, 0x2b, 0xe4, 0xe3, 0x10, 0x5a, 0xb9, 0xfd,
	0x8c, 0x7e, 0x0f, 0xe0, 0xce, 0xfa, 0x2a, 0xe4, 0x29, 0x74, 0xe7, 0xb8, 0x1a, 0x2e, 0x51, 0x48,
	0xc6, 0x33, 0xd9, 0x0b, 0xf6, 0x6a, 0xfb, 0x9d, 0x03, 0x52, 0x68, 0xc2, 0xd5, 0x1b, 0xeb, 0xa2,
	0x9d, 0x79, 0xf1, 0x2d, 0xc9, 0x01, 0x84, 0x4c, 0x89, 0x21, 0xcb, 0xa6, 0x5c, 0xef, 0x43, 0xc7,
	0xdc, 0xf7, 0x31, 0xa7, 0x0a, 0x45, 0xac, 0x18, 0xcf, 0x4e, 0xb3, 0x29, 0xa7, 0x6d, 0xa6, 0x84,
	0xfe, 0x90, 0xe4, 0x93, 0x42, 0x48, 0xaf, 0x66, 0x22, 0xee, 0x56, 0x57, 0x89, 0x93, 0x1c, 0xa9,
	0x27, 0x90, 0x1e, 0xb4, 0x26, 0x98, 0xa0, 0xe6, 0xd6, 0xf7, 0x6a, 0xfb, 0x21, 0xf5, 0x66, 0x74,
	0x0e, 0x6d, 0x4f, 0x27, 0x77, 0xa1, 0x36, 0xc7, 0x95, 0xab, 0xb2, 0xfe, 0x24, 0xf7, 0xa0, 0xb1,
	0xd4, 0x2e, 0x53, 0xdb, 0x2e, 0xb5, 0x86, 0xee, 0x89, 0x64, 0xb3, 0x2c, 0x56, 0xb9, 0x40, 0x53,
	0xbc, 0x2e, 0x2d, 0x81, 0xe8, 0x14, 0xa0, 0xdc, 0xe6, 0x5b, 0x72, 0x7e, 0x0c, 0x2d, 0x57, 0x1e,
	0xd7, 0xb1, 0x6d, 0xaf, 0xdb, 0x97, 0xc6, 0xfb, 0xa3, 0x14, 0xba, 0x46, 0x99, 0x4f, 0x56, 0xc8,
	0x09, 0xaa, 0x72, 0xfe, 0x7b, 0xc2, 0x7f, 0x51, 0xfe, 0x25, 0xb4, 0xfc, 0x4a, 0xef, 0x43, 0x38,
	0x4a, 0xf8, 0x78, 0x3e, 0xcc, 0xf2, 0xd4, 0xac, 0x56, 0xa7, 0x6d, 0x03, 0x9c, 0xe5, 0x29, 0xb9,
	0x0f, 0x4d, 0x75, 0x63, 0x3c, 0x7a, 0xbd, 0x06, 0x6d, 0xa8, 0x9b, 0xb3, 0x3c, 0x8d, 0x7e, 0x0e,
	0x60, 0x6b, 0xad, 0x59, 0x3a, 0x8b, 0x54, 0xb1, 0x50, 0xc3, 0xb2, 0x04, 0x6d, 0x03, 0xbc, 0xc2,
	0x15, 0x79, 0x00, 0x2d, 0xcc, 0x26, 0xc6, 0xb5, 0x69, 0x5c, 0x4d, 0xcc, 0x26, 0xda, 0xf1, 0x10,
	0x42, 0x96, 0x8d, 0x93, 0x5c, 0xb2, 0xa5, 0x15, 0xd9, 0xa6, 0x25, 0x40, 0x3e, 0x82, 0xba, 0x12,
	0x88, 0xbd, 0xba, 0xd9, 0x6a, 0x71, 0xb2, 0xbe, 0x45, 0x31, 0x4f, 0xf0, 0x42, 0x20, 0x52, 0xe3,
	0x8f, 0x3e, 0x07, 0x28, 0x31, 0x5d, 0xb9, 0x04, 0x97, 0x98, 0x18, 0x15, 0x0d, 0x6a, 0x0d, 0x8d,
	0x66, 0x7c, 0x82, 0xf6, 0xc8, 0x75, 0xa9, 0x35, 0xa2, 0x17, 0xd0, 0x3d, 0xd6, 0x5b, 0x3d, 0xe7,
	0x2c, 0x53, 0x28, 0xc8, 0x7b, 0xd0, 0x9e, 0xb2, 0x04, 0x8b, 0x52, 0x34, 0x68, 0x4b, 0xdb, 0xba,
	0x12, 0x3b, 0xd0, 0xe4, 0xd3, 0xa9, 0x44, 0xe5, 0x2a, 0xe1, 0xac, 0xe8, 0xa7, 0x00, 0xb6, 0x6f,
	0x5d, 0x23, 0xf2, 0x0c, 0xba, 0x12, 0x13, 0x1c, 0xab, 0xa1, 0x54, 0xa9, 0xf2, 0x57, 0xa3, 0xbc,
	0x75, 0xc6, 0x67, 0x22, 0x52, 0xcc, 0x14, 0xed, 0x48, 0x07, 0xa4, 0xca, 0xc4, 0xb2, 0x4c, 0xa2,
	0xf0, 0xb1, 0x9b, 0xeb, 0xb1, 0xa7, 0xc6, 0x57, 0x89, 0x65, 0x0e, 0x48, 0x95, 0x8c, 0x7e, 0xd5,
	0x5a, 0xd6, 0x93, 0xeb, 0x8d, 0x5f, 0xe5, 0x28, 0x7c, 0x53, 0xac, 0x41, 0x3e, 0x85, 0x7a, 0x2c,
	0x66, 0x7e, 0x90, 0x14, 0xd9, 0xcf, 0x05, 0x4b, 0x99, 0x62, 0x4b, 0x34, 0x67, 0x51, 0x52, 0x43,
	0x2a, 0xfa, 0x50, 0xfb, 0xe7, 0x3e, 0x98, 0x01, 0x96, 0xa7, 0xdf, 0x4d, 0x29, 0xbf, 0x96, 0xa6,
	0x69, 0x75, 0x5a, 0x02, 0xd1, 0x1f, 0x01, 0x6c, 0xdf, 0x52, 0x4f, 0x3e, 0x00, 0x50, 0xf1, 0x48,
	0x17, 0x3c, 0x4e, 0x8b, 0x99, 0x67, 0x90, 0xb3, 0x38, 0x45, 0x7d, 0x97, 0xc7, 0x3c, 0xc9, 0xd3,
	0xcc, 0x96, 0x21, 0xa4, 0xde, 0x24, 0xcf, 0x61, 0xcb, 0x55, 0xc9, 0x5c, 0x0c, 0x3f, 0xd8, 0xee,
	0xad, 0x97, 0xc9, 0xee, 0xe2, 0x64, 0x83, 0xba, 0x92, 0x5a, 0x9b, 0x3c, 0x03, 0x57, 0xf1, 0xa1,
	0xf0, 0x4a, 0xff, 0xbe, 0x3b, 0x66, 0x26, 0x1a, 0x48, 0xef, 0x82, 0xec, 0x42, 0x9b, 0xc9, 0x97,
	0x66, 0xa2, 0xf4, 0x1a, 0xe6, 0xc0, 0x16, 0xf6, 0x71, 0x1b, 0x9a, 0x56, 0x4d, 0xf4, 0x12, 0xba,
	0x55, 0x05, 0xe4, 0x10, 0x3a, 0xc6, 0x73, 0x91, 0x2f, 0x12, 0xfc, 0xcb, 0xa8, 0x7c, 0x53, 0xb8,
	0x68, 0x95, 0x16, 0x7d, 0x05, 0x50, 0xba, 0xc8, 0x67, 0x00, 0xc6, 0xf9, 0xf5, 0xcd, 0x42, 0xf8,
	0x14, 0xef, 0xac, 0xa5, 0xd0, 0x1e, 0x5a, 0x21, 0x45, 0xdf, 0x40, 0x58, 0x38, 0x08, 0x81, 0x3a,
	0xde, 0x2c, 0x84, 0xab, 0xb2, 0xf9, 0xfe, 0x5f, 0xc7, 0x20, 0x7a, 0x01, 0xdb, 0xb7, 0x1c, 0xa4,
	0xef, 0x77, 0xec, 0xf4, 0xec, 0xbc, 0x3d, 0x03, 0xf5, 0x75, 0xf9, 0xa5, 0x06, 0x77, 0xd6, 0x5d,
	0xe4, 0x31, 0x74, 0x27, 0x3c, 0xd7, 0x67, 0xa0, 0x9c, 0x77, 0xc1, 0xc9, 0x06, 0xed, 0x58, 0xd4,
	0x92, 0x3e, 0x84, 0xce, 0x34, 0xe1, 0xb1, 0xeb, 0xb6, 0x91, 0xbb, 0xa9, 0x1b, 0x63, 0xc0, 0x82,
	0xc2, 0x32, 0xf5, 0xe4, 0xc0, 0x51, 0xf4, 0x79, 0x68, 0x68, 0x8a, 0x01, 0xab, 0x94, 0xa3, 0x43,
	0x47, 0xd1, 0x7d, 0xaf, 0x39, 0xca, 0xd1, 0x61, 0xa1, 0x26, 0xaf, 0xa6, 0xd1, 0x2d, 0xde, 0xd2,
	0x6a, 0xf2, 0x4a, 0x1e, 0x47, 0x2a, 0x12, 0x35, 0xf5, 0x51, 0xf7, 0x24, 0x9f, 0xe9, 0x11, 0xc0,
	0x88, 0xf3, 0xc4, 0x51, 0x5a, 0xfa, 0xa8, 0xe8, 0x1f, 0xb3, 0xc6, 0x8a, 0x2c, 0x52, 0x09, 0x96,
	0xcd, 0x1c, 0xa5, 0xad, 0xfb, 0xa2, 0xb3, 0x58, 0xb4, 0x90, 0x3c, 0x5a, 0x29, 0x94, 0x8e, 0x13,
	0xea, 0x39, 0xae, 0x25, 0x1b, 0xd0, 0x52, 0x9e, 0x03, 0xe8, 0xa7, 0x85, 0x63, 0x80, 0xe9, 0xe4,
	0x6e, 0xdf, 0xbe, 0x3e, 0xfa, 0xfe, 0xf5, 0xd1, 0xbf, 0xf0, 0xaf, 0x0f, 0x2d, 0x42, 0xf3, 0x4d,
	0xf0, 0x71, 0xcb, 0xfd, 0x66, 0x8e, 0x7f, 0x84, 0xc7, 0x63, 0x9e, 0xf6, 0x2f, 0xf3, 0xf8, 0x1a,
	0x59, 0xff, 0x9a, 0x61, 0x86, 0x62, 0x7c, 0x19, 0xb3, 0xcc, 0xa6, 0x70, 0x7d, 0xfd, 0xe1, 0xe9,
	0x8c, 0x29, 0x4f, 0x1a, 0xf3, 0x74, 0xb0, 0xe0, 0x4c, 0x4a, 0x9e, 0x49, 0x8c, 0xc5, 0xf8, 0x72,
	0x50, 0x09, 0xb3, 0xef, 0x9e, 0x81, 0x0d, 0x1b, 0x35, 0x8d, 0xf5, 0xe4, 0xcf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa8, 0xd7, 0x34, 0xef, 0x32, 0x09, 0x00, 0x00,
}
