// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/message.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_UNKNOWN                  Status = 0
	Status_SUCCESS                  Status = 200
	Status_BAD_REQUEST              Status = 400
	Status_FORBIDDEN                Status = 403
	Status_NOT_FOUND                Status = 404
	Status_REQUEST_ENTITY_TOO_LARGE Status = 413
	Status_INTERNAL_SERVER_ERROR    Status = 500
	Status_NOT_IMPLEMENTED          Status = 501
	Status_SERVICE_UNAVAILABLE      Status = 503
)

var Status_name = map[int32]string{
	0:   "UNKNOWN",
	200: "SUCCESS",
	400: "BAD_REQUEST",
	403: "FORBIDDEN",
	404: "NOT_FOUND",
	413: "REQUEST_ENTITY_TOO_LARGE",
	500: "INTERNAL_SERVER_ERROR",
	501: "NOT_IMPLEMENTED",
	503: "SERVICE_UNAVAILABLE",
}

var Status_value = map[string]int32{
	"UNKNOWN":                  0,
	"SUCCESS":                  200,
	"BAD_REQUEST":              400,
	"FORBIDDEN":                403,
	"NOT_FOUND":                404,
	"REQUEST_ENTITY_TOO_LARGE": 413,
	"INTERNAL_SERVER_ERROR":    500,
	"NOT_IMPLEMENTED":          501,
	"SERVICE_UNAVAILABLE":      503,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8de410db4f60bbbc, []int{0}
}

// RawMessage is the message that delivers through grpc service.
// If RawMessage is a request message, the payload is the info
// for the request, i.e. CreateInfo.  If RawMessge is a response
// message, in most cases the payload is Response defined below,
// but it can be any other struct based on actual requirement.
type RawMessage struct {
	Signature            *RawMessage_Signature `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Payload              []byte                `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RawMessage) Reset()         { *m = RawMessage{} }
func (m *RawMessage) String() string { return proto.CompactTextString(m) }
func (*RawMessage) ProtoMessage()    {}
func (*RawMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de410db4f60bbbc, []int{0}
}

func (m *RawMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawMessage.Unmarshal(m, b)
}
func (m *RawMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawMessage.Marshal(b, m, deterministic)
}
func (m *RawMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawMessage.Merge(m, src)
}
func (m *RawMessage) XXX_Size() int {
	return xxx_messageInfo_RawMessage.Size(m)
}
func (m *RawMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RawMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RawMessage proto.InternalMessageInfo

func (m *RawMessage) GetSignature() *RawMessage_Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *RawMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type RawMessage_Signature struct {
	Cert                 []byte   `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Sign                 []byte   `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawMessage_Signature) Reset()         { *m = RawMessage_Signature{} }
func (m *RawMessage_Signature) String() string { return proto.CompactTextString(m) }
func (*RawMessage_Signature) ProtoMessage()    {}
func (*RawMessage_Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de410db4f60bbbc, []int{0, 0}
}

func (m *RawMessage_Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawMessage_Signature.Unmarshal(m, b)
}
func (m *RawMessage_Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawMessage_Signature.Marshal(b, m, deterministic)
}
func (m *RawMessage_Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawMessage_Signature.Merge(m, src)
}
func (m *RawMessage_Signature) XXX_Size() int {
	return xxx_messageInfo_RawMessage_Signature.Size(m)
}
func (m *RawMessage_Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_RawMessage_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_RawMessage_Signature proto.InternalMessageInfo

func (m *RawMessage_Signature) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *RawMessage_Signature) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type Response struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=common.Status" json:"status,omitempty"`
	StatusInfo           string   `protobuf:"bytes,2,opt,name=status_info,json=statusInfo,proto3" json:"status_info,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de410db4f60bbbc, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

func (m *Response) GetStatusInfo() string {
	if m != nil {
		return m.StatusInfo
	}
	return ""
}

func (m *Response) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type StatusResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=common.Status" json:"status,omitempty"`
	StatusInfo           string   `protobuf:"bytes,2,opt,name=status_info,json=statusInfo,proto3" json:"status_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de410db4f60bbbc, []int{2}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

func (m *StatusResponse) GetStatusInfo() string {
	if m != nil {
		return m.StatusInfo
	}
	return ""
}

func init() {
	proto.RegisterEnum("common.Status", Status_name, Status_value)
	proto.RegisterType((*RawMessage)(nil), "common.RawMessage")
	proto.RegisterType((*RawMessage_Signature)(nil), "common.RawMessage.Signature")
	proto.RegisterType((*Response)(nil), "common.Response")
	proto.RegisterType((*StatusResponse)(nil), "common.StatusResponse")
}

func init() {
	proto.RegisterFile("common/message.proto", fileDescriptor_8de410db4f60bbbc)
}

var fileDescriptor_8de410db4f60bbbc = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x8d, 0x91, 0xd6, 0xbe, 0x96, 0x3a, 0x8c, 0x2b, 0x84, 0x45, 0x71, 0xa9, 0x20, 0x8b,
	0x87, 0x04, 0x76, 0xf1, 0xe2, 0x2d, 0x6d, 0x66, 0x25, 0x98, 0x4e, 0x74, 0x92, 0xac, 0xac, 0x08,
	0xc3, 0x18, 0x67, 0xdb, 0x80, 0xc9, 0x94, 0x4c, 0x4a, 0xf1, 0x5b, 0x08, 0x0a, 0x9e, 0xfc, 0x2e,
	0x1e, 0xfd, 0x40, 0x8a, 0x57, 0xc9, 0x24, 0x75, 0xd7, 0xbb, 0xb7, 0xf7, 0xfe, 0xef, 0xff, 0xfb,
	0xcf, 0xe3, 0x31, 0x70, 0x90, 0xab, 0xb2, 0x54, 0x95, 0x57, 0x4a, 0xad, 0xc5, 0x4a, 0xba, 0x9b,
	0x5a, 0x35, 0x0a, 0x0f, 0x3a, 0x75, 0xf6, 0xd5, 0x02, 0x60, 0x62, 0xb7, 0xec, 0x86, 0xf8, 0x19,
	0x8c, 0x74, 0xb1, 0xaa, 0x44, 0xb3, 0xad, 0xa5, 0x63, 0x1d, 0x59, 0xc7, 0xe3, 0x93, 0xfb, 0x6e,
	0x67, 0x75, 0xaf, 0x6c, 0x6e, 0xb2, 0xf7, 0xb0, 0x2b, 0x3b, 0x76, 0x60, 0xb8, 0x11, 0x1f, 0x3f,
	0x28, 0xf1, 0xde, 0xb9, 0x79, 0x64, 0x1d, 0x4f, 0xd8, 0xbe, 0x3d, 0x3c, 0x85, 0xd1, 0x5f, 0x02,
	0x63, 0xb8, 0x95, 0xcb, 0xba, 0x31, 0xe9, 0x13, 0x66, 0xea, 0x56, 0x6b, 0x73, 0x7a, 0xce, 0xd4,
	0xb3, 0x12, 0x6e, 0x33, 0xa9, 0x37, 0xaa, 0xd2, 0x12, 0x3f, 0x86, 0x81, 0x6e, 0x44, 0xb3, 0xd5,
	0x86, 0x9a, 0x9e, 0x4c, 0xf7, 0x3b, 0x25, 0x46, 0x65, 0xfd, 0x14, 0x3f, 0x84, 0x71, 0x57, 0xf1,
	0xa2, 0xba, 0x54, 0x26, 0x6e, 0xc4, 0xa0, 0x93, 0xc2, 0xea, 0x52, 0x5d, 0xdf, 0xd1, 0xfe, 0x67,
	0xc7, 0xd9, 0x05, 0x4c, 0xfb, 0xb0, 0xff, 0xfd, 0xe8, 0x93, 0xef, 0x16, 0x0c, 0x3a, 0x06, 0x8f,
	0x61, 0x98, 0xd1, 0x17, 0x34, 0x7e, 0x4d, 0xd1, 0x0d, 0x3c, 0x81, 0x61, 0x92, 0x2d, 0x16, 0x24,
	0x49, 0xd0, 0x0f, 0x0b, 0x23, 0x18, 0xcf, 0xfd, 0x80, 0x33, 0xf2, 0x2a, 0x23, 0x49, 0x8a, 0x3e,
	0xd9, 0x78, 0x0a, 0xa3, 0xb3, 0x98, 0xcd, 0xc3, 0x20, 0x20, 0x14, 0x7d, 0x36, 0x3d, 0x8d, 0x53,
	0x7e, 0x16, 0x67, 0x34, 0x40, 0x5f, 0x6c, 0xfc, 0x00, 0x9c, 0xde, 0xcd, 0x09, 0x4d, 0xc3, 0xf4,
	0x82, 0xa7, 0x71, 0xcc, 0x23, 0x9f, 0x3d, 0x27, 0xe8, 0x9b, 0x8d, 0x0f, 0xe1, 0x5e, 0x48, 0x53,
	0xc2, 0xa8, 0x1f, 0xf1, 0x84, 0xb0, 0x73, 0xc2, 0x38, 0x61, 0x2c, 0x66, 0xe8, 0xa7, 0x8d, 0x0f,
	0xe0, 0x4e, 0x1b, 0x15, 0x2e, 0x5f, 0x46, 0x64, 0x49, 0x68, 0x4a, 0x02, 0xf4, 0xcb, 0xc6, 0x0e,
	0xdc, 0x6d, 0x8d, 0xe1, 0x82, 0xf0, 0x8c, 0xfa, 0xe7, 0x7e, 0x18, 0xf9, 0xf3, 0x88, 0xa0, 0xdf,
	0xf6, 0xfc, 0x2d, 0x3c, 0xca, 0x55, 0xe9, 0xae, 0xb7, 0x62, 0x27, 0x0b, 0x77, 0x57, 0xc8, 0x4a,
	0xd6, 0xf9, 0x5a, 0x14, 0x55, 0xf7, 0x9d, 0xfa, 0xcb, 0xbc, 0x79, 0xba, 0x2a, 0x9a, 0xbd, 0x29,
	0x57, 0xa5, 0xb7, 0x51, 0x85, 0xd6, 0xed, 0x31, 0x45, 0x9d, 0xaf, 0xbd, 0x6b, 0x98, 0x67, 0x30,
	0xaf, 0xc3, 0xde, 0x0d, 0x4c, 0x77, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xf7, 0xfe, 0x0c,
	0xab, 0x02, 0x00, 0x00,
}
