// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/policy.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operator int32

const (
	Operator_AND Operator = 0
	Operator_OR  Operator = 1
)

var Operator_name = map[int32]string{
	0: "AND",
	1: "OR",
}

var Operator_value = map[string]int32{
	"AND": 0,
	"OR":  1,
}

func (x Operator) String() string {
	return proto.EnumName(Operator_name, int32(x))
}

func (Operator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7e7bd80df9edbf49, []int{0}
}

type Policy struct {
	// Types that are valid to be assigned to Ast:
	//	*Policy_NonTerminal
	//	*Policy_Terminal
	Ast                  isPolicy_Ast `protobuf_oneof:"ast"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e7bd80df9edbf49, []int{0}
}

func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (m *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(m, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

type isPolicy_Ast interface {
	isPolicy_Ast()
}

type Policy_NonTerminal struct {
	NonTerminal *NonTerminal `protobuf:"bytes,1,opt,name=non_terminal,json=nonTerminal,proto3,oneof"`
}

type Policy_Terminal struct {
	Terminal *Terminal `protobuf:"bytes,2,opt,name=terminal,proto3,oneof"`
}

func (*Policy_NonTerminal) isPolicy_Ast() {}

func (*Policy_Terminal) isPolicy_Ast() {}

func (m *Policy) GetAst() isPolicy_Ast {
	if m != nil {
		return m.Ast
	}
	return nil
}

func (m *Policy) GetNonTerminal() *NonTerminal {
	if x, ok := m.GetAst().(*Policy_NonTerminal); ok {
		return x.NonTerminal
	}
	return nil
}

func (m *Policy) GetTerminal() *Terminal {
	if x, ok := m.GetAst().(*Policy_Terminal); ok {
		return x.Terminal
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Policy) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Policy_NonTerminal)(nil),
		(*Policy_Terminal)(nil),
	}
}

type NonTerminal struct {
	Op                   Operator `protobuf:"varint,1,opt,name=op,proto3,enum=common.Operator" json:"op,omitempty"`
	LeftToken            *Policy  `protobuf:"bytes,2,opt,name=left_token,json=leftToken,proto3" json:"left_token,omitempty"`
	RightToken           *Policy  `protobuf:"bytes,3,opt,name=right_token,json=rightToken,proto3" json:"right_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonTerminal) Reset()         { *m = NonTerminal{} }
func (m *NonTerminal) String() string { return proto.CompactTextString(m) }
func (*NonTerminal) ProtoMessage()    {}
func (*NonTerminal) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e7bd80df9edbf49, []int{1}
}

func (m *NonTerminal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonTerminal.Unmarshal(m, b)
}
func (m *NonTerminal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonTerminal.Marshal(b, m, deterministic)
}
func (m *NonTerminal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonTerminal.Merge(m, src)
}
func (m *NonTerminal) XXX_Size() int {
	return xxx_messageInfo_NonTerminal.Size(m)
}
func (m *NonTerminal) XXX_DiscardUnknown() {
	xxx_messageInfo_NonTerminal.DiscardUnknown(m)
}

var xxx_messageInfo_NonTerminal proto.InternalMessageInfo

func (m *NonTerminal) GetOp() Operator {
	if m != nil {
		return m.Op
	}
	return Operator_AND
}

func (m *NonTerminal) GetLeftToken() *Policy {
	if m != nil {
		return m.LeftToken
	}
	return nil
}

func (m *NonTerminal) GetRightToken() *Policy {
	if m != nil {
		return m.RightToken
	}
	return nil
}

type Terminal struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Terminal) Reset()         { *m = Terminal{} }
func (m *Terminal) String() string { return proto.CompactTextString(m) }
func (*Terminal) ProtoMessage()    {}
func (*Terminal) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e7bd80df9edbf49, []int{2}
}

func (m *Terminal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Terminal.Unmarshal(m, b)
}
func (m *Terminal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Terminal.Marshal(b, m, deterministic)
}
func (m *Terminal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Terminal.Merge(m, src)
}
func (m *Terminal) XXX_Size() int {
	return xxx_messageInfo_Terminal.Size(m)
}
func (m *Terminal) XXX_DiscardUnknown() {
	xxx_messageInfo_Terminal.DiscardUnknown(m)
}

var xxx_messageInfo_Terminal proto.InternalMessageInfo

func (m *Terminal) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("common.Operator", Operator_name, Operator_value)
	proto.RegisterType((*Policy)(nil), "common.Policy")
	proto.RegisterType((*NonTerminal)(nil), "common.NonTerminal")
	proto.RegisterType((*Terminal)(nil), "common.Terminal")
}

func init() {
	proto.RegisterFile("common/policy.proto", fileDescriptor_7e7bd80df9edbf49)
}

var fileDescriptor_7e7bd80df9edbf49 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd7, 0x8e, 0xd5, 0xed, 0x55, 0xc6, 0xc8, 0x3c, 0x08, 0x5e, 0xc6, 0xbc, 0x88, 0x60,
	0x02, 0x8a, 0xe0, 0xd5, 0xe1, 0xc1, 0xd3, 0x26, 0x65, 0x27, 0x11, 0x46, 0x0c, 0x71, 0x0d, 0xb6,
	0x79, 0x21, 0x8d, 0x8c, 0x7d, 0x0a, 0xbf, 0xb2, 0x34, 0x69, 0xbb, 0x1e, 0x3c, 0xbe, 0xd7, 0xdf,
	0xef, 0xfd, 0xff, 0x0d, 0xcc, 0x05, 0x96, 0x25, 0x6a, 0x66, 0xb0, 0x50, 0xe2, 0x48, 0x8d, 0x45,
	0x87, 0x24, 0x09, 0xcb, 0xe5, 0x11, 0x92, 0x37, 0xbf, 0x27, 0x4f, 0x70, 0xae, 0x51, 0xef, 0x9c,
	0xb4, 0xa5, 0xd2, 0xbc, 0xb8, 0x8c, 0x16, 0xd1, 0x4d, 0x7a, 0x3f, 0xa7, 0x01, 0xa4, 0x6b, 0xd4,
	0xdb, 0xe6, 0xd3, 0xeb, 0x20, 0x4b, 0xf5, 0x69, 0x24, 0x14, 0xc6, 0x9d, 0x15, 0x7b, 0x6b, 0xd6,
	0x5a, 0x3d, 0xa5, 0x63, 0x56, 0x23, 0x18, 0xf2, 0xca, 0x2d, 0x7f, 0x23, 0x48, 0x7b, 0x57, 0xc9,
	0x02, 0x62, 0x34, 0x3e, 0x76, 0x7a, 0x3a, 0xb0, 0x31, 0xd2, 0x72, 0x87, 0x36, 0x8b, 0xd1, 0x90,
	0x3b, 0x80, 0x42, 0x7e, 0xb9, 0x9d, 0xc3, 0x6f, 0xa9, 0x9b, 0xa8, 0x69, 0x4b, 0x86, 0xdf, 0xc8,
	0x26, 0x35, 0xb1, 0xad, 0x01, 0xc2, 0x20, 0xb5, 0x6a, 0x9f, 0xb7, 0xfc, 0xf0, 0x5f, 0x1e, 0x3c,
	0xe2, 0x85, 0xe5, 0x02, 0xc6, 0x5d, 0x9b, 0x0b, 0x18, 0x05, 0xad, 0x2e, 0x34, 0xc9, 0xc2, 0x70,
	0x7b, 0x05, 0xe3, 0xb6, 0x11, 0x39, 0x83, 0xe1, 0xf3, 0xfa, 0x65, 0x36, 0x20, 0x09, 0xc4, 0x9b,
	0x6c, 0x16, 0xad, 0x3e, 0xe0, 0x5a, 0x60, 0x49, 0xf3, 0x1f, 0x7e, 0x90, 0x8a, 0x1e, 0x94, 0xd4,
	0xd2, 0x8a, 0x9c, 0x2b, 0x1d, 0xde, 0xbc, 0x09, 0x7e, 0x7f, 0xdc, 0x2b, 0xd7, 0x42, 0x02, 0x4b,
	0x66, 0x50, 0x55, 0x15, 0xea, 0x4a, 0x72, 0x2b, 0x72, 0xd6, 0xd3, 0x98, 0xd7, 0x58, 0xd0, 0x3e,
	0x13, 0x3f, 0x3d, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0x13, 0x01, 0x21, 0xc2, 0xcf, 0x01, 0x00,
	0x00,
}
