// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contract/contract.proto

package contract

import (
	context "context"
	fmt "fmt"
	common "git.huawei.com/poissonsearch/wienerchain/proto/common"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContractMsg_Type int32

const (
	ContractMsg_UNDEFINED           ContractMsg_Type = 0
	ContractMsg_INIT                ContractMsg_Type = 1
	ContractMsg_INVOKE              ContractMsg_Type = 2
	ContractMsg_GET_KV              ContractMsg_Type = 3
	ContractMsg_PUT_KV              ContractMsg_Type = 4
	ContractMsg_DEL_KV              ContractMsg_Type = 5
	ContractMsg_GET_KV_BY_RANGE     ContractMsg_Type = 6
	ContractMsg_GET_HISTORY_FOR_KEY ContractMsg_Type = 7
	ContractMsg_SQL_INIT            ContractMsg_Type = 8
	ContractMsg_SQL_INVOKE          ContractMsg_Type = 9
	ContractMsg_SQL_EXEC            ContractMsg_Type = 10
	ContractMsg_SQL_QUERY           ContractMsg_Type = 11
)

var ContractMsg_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "INIT",
	2:  "INVOKE",
	3:  "GET_KV",
	4:  "PUT_KV",
	5:  "DEL_KV",
	6:  "GET_KV_BY_RANGE",
	7:  "GET_HISTORY_FOR_KEY",
	8:  "SQL_INIT",
	9:  "SQL_INVOKE",
	10: "SQL_EXEC",
	11: "SQL_QUERY",
}

var ContractMsg_Type_value = map[string]int32{
	"UNDEFINED":           0,
	"INIT":                1,
	"INVOKE":              2,
	"GET_KV":              3,
	"PUT_KV":              4,
	"DEL_KV":              5,
	"GET_KV_BY_RANGE":     6,
	"GET_HISTORY_FOR_KEY": 7,
	"SQL_INIT":            8,
	"SQL_INVOKE":          9,
	"SQL_EXEC":            10,
	"SQL_QUERY":           11,
}

func (x ContractMsg_Type) String() string {
	return proto.EnumName(ContractMsg_Type_name, int32(x))
}

func (ContractMsg_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{6, 0}
}

type ContractDefinition struct {
	ContractName         string            `protobuf:"bytes,1,opt,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	SchemaVersion        string            `protobuf:"bytes,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	SequenceNumber       uint32            `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Description          string            `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RequireInit          bool              `protobuf:"varint,5,opt,name=require_init,json=requireInit,proto3" json:"require_init,omitempty"`
	SqlDbSchema          string            `protobuf:"bytes,6,opt,name=sql_db_schema,json=sqlDbSchema,proto3" json:"sql_db_schema,omitempty"`
	HistorySupport       bool              `protobuf:"varint,7,opt,name=history_support,json=historySupport,proto3" json:"history_support,omitempty"`
	ApprovalValidator    string            `protobuf:"bytes,10,opt,name=approval_validator,json=approvalValidator,proto3" json:"approval_validator,omitempty"`
	ValidatorExtensions  map[string][]byte `protobuf:"bytes,11,rep,name=validator_extensions,json=validatorExtensions,proto3" json:"validator_extensions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ContractDefinition) Reset()         { *m = ContractDefinition{} }
func (m *ContractDefinition) String() string { return proto.CompactTextString(m) }
func (*ContractDefinition) ProtoMessage()    {}
func (*ContractDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{0}
}

func (m *ContractDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractDefinition.Unmarshal(m, b)
}
func (m *ContractDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractDefinition.Marshal(b, m, deterministic)
}
func (m *ContractDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractDefinition.Merge(m, src)
}
func (m *ContractDefinition) XXX_Size() int {
	return xxx_messageInfo_ContractDefinition.Size(m)
}
func (m *ContractDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_ContractDefinition proto.InternalMessageInfo

func (m *ContractDefinition) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ContractDefinition) GetSchemaVersion() string {
	if m != nil {
		return m.SchemaVersion
	}
	return ""
}

func (m *ContractDefinition) GetSequenceNumber() uint32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *ContractDefinition) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ContractDefinition) GetRequireInit() bool {
	if m != nil {
		return m.RequireInit
	}
	return false
}

func (m *ContractDefinition) GetSqlDbSchema() string {
	if m != nil {
		return m.SqlDbSchema
	}
	return ""
}

func (m *ContractDefinition) GetHistorySupport() bool {
	if m != nil {
		return m.HistorySupport
	}
	return false
}

func (m *ContractDefinition) GetApprovalValidator() string {
	if m != nil {
		return m.ApprovalValidator
	}
	return ""
}

func (m *ContractDefinition) GetValidatorExtensions() map[string][]byte {
	if m != nil {
		return m.ValidatorExtensions
	}
	return nil
}

type DockerImageInfo struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	RepoTag              string   `protobuf:"bytes,2,opt,name=repo_tag,json=repoTag,proto3" json:"repo_tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockerImageInfo) Reset()         { *m = DockerImageInfo{} }
func (m *DockerImageInfo) String() string { return proto.CompactTextString(m) }
func (*DockerImageInfo) ProtoMessage()    {}
func (*DockerImageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{1}
}

func (m *DockerImageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockerImageInfo.Unmarshal(m, b)
}
func (m *DockerImageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockerImageInfo.Marshal(b, m, deterministic)
}
func (m *DockerImageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockerImageInfo.Merge(m, src)
}
func (m *DockerImageInfo) XXX_Size() int {
	return xxx_messageInfo_DockerImageInfo.Size(m)
}
func (m *DockerImageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DockerImageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DockerImageInfo proto.InternalMessageInfo

func (m *DockerImageInfo) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DockerImageInfo) GetRepoTag() string {
	if m != nil {
		return m.RepoTag
	}
	return ""
}

type ExternalContractInfo struct {
	SandboxType          string            `protobuf:"bytes,1,opt,name=sandbox_type,json=sandboxType,proto3" json:"sandbox_type,omitempty"`
	SchemaVersion        string            `protobuf:"bytes,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Code                 []byte            `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	PeerCert             []byte            `protobuf:"bytes,4,opt,name=peer_cert,json=peerCert,proto3" json:"peer_cert,omitempty"`
	Extensions           map[string]string `protobuf:"bytes,5,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExternalContractInfo) Reset()         { *m = ExternalContractInfo{} }
func (m *ExternalContractInfo) String() string { return proto.CompactTextString(m) }
func (*ExternalContractInfo) ProtoMessage()    {}
func (*ExternalContractInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{2}
}

func (m *ExternalContractInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalContractInfo.Unmarshal(m, b)
}
func (m *ExternalContractInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalContractInfo.Marshal(b, m, deterministic)
}
func (m *ExternalContractInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalContractInfo.Merge(m, src)
}
func (m *ExternalContractInfo) XXX_Size() int {
	return xxx_messageInfo_ExternalContractInfo.Size(m)
}
func (m *ExternalContractInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalContractInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalContractInfo proto.InternalMessageInfo

func (m *ExternalContractInfo) GetSandboxType() string {
	if m != nil {
		return m.SandboxType
	}
	return ""
}

func (m *ExternalContractInfo) GetSchemaVersion() string {
	if m != nil {
		return m.SchemaVersion
	}
	return ""
}

func (m *ExternalContractInfo) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ExternalContractInfo) GetPeerCert() []byte {
	if m != nil {
		return m.PeerCert
	}
	return nil
}

func (m *ExternalContractInfo) GetExtensions() map[string]string {
	if m != nil {
		return m.Extensions
	}
	return nil
}

type ContractConfig struct {
	TlsConfig            *ContractTLSConfig  `protobuf:"bytes,1,opt,name=tls_config,json=tlsConfig,proto3" json:"tls_config,omitempty"`
	GrpcConfig           *ContractGRPCConfig `protobuf:"bytes,2,opt,name=grpc_config,json=grpcConfig,proto3" json:"grpc_config,omitempty"`
	Port                 string              `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	LogLevel             string              `protobuf:"bytes,4,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ContractConfig) Reset()         { *m = ContractConfig{} }
func (m *ContractConfig) String() string { return proto.CompactTextString(m) }
func (*ContractConfig) ProtoMessage()    {}
func (*ContractConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{3}
}

func (m *ContractConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractConfig.Unmarshal(m, b)
}
func (m *ContractConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractConfig.Marshal(b, m, deterministic)
}
func (m *ContractConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractConfig.Merge(m, src)
}
func (m *ContractConfig) XXX_Size() int {
	return xxx_messageInfo_ContractConfig.Size(m)
}
func (m *ContractConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ContractConfig proto.InternalMessageInfo

func (m *ContractConfig) GetTlsConfig() *ContractTLSConfig {
	if m != nil {
		return m.TlsConfig
	}
	return nil
}

func (m *ContractConfig) GetGrpcConfig() *ContractGRPCConfig {
	if m != nil {
		return m.GrpcConfig
	}
	return nil
}

func (m *ContractConfig) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *ContractConfig) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

type ContractGRPCConfig struct {
	Interval             uint32   `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout              uint32   `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MinInterval          uint32   `protobuf:"varint,3,opt,name=minInterval,proto3" json:"minInterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractGRPCConfig) Reset()         { *m = ContractGRPCConfig{} }
func (m *ContractGRPCConfig) String() string { return proto.CompactTextString(m) }
func (*ContractGRPCConfig) ProtoMessage()    {}
func (*ContractGRPCConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{4}
}

func (m *ContractGRPCConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractGRPCConfig.Unmarshal(m, b)
}
func (m *ContractGRPCConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractGRPCConfig.Marshal(b, m, deterministic)
}
func (m *ContractGRPCConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractGRPCConfig.Merge(m, src)
}
func (m *ContractGRPCConfig) XXX_Size() int {
	return xxx_messageInfo_ContractGRPCConfig.Size(m)
}
func (m *ContractGRPCConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractGRPCConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ContractGRPCConfig proto.InternalMessageInfo

func (m *ContractGRPCConfig) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *ContractGRPCConfig) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *ContractGRPCConfig) GetMinInterval() uint32 {
	if m != nil {
		return m.MinInterval
	}
	return 0
}

type ContractTLSConfig struct {
	IsTlsEnabled         bool     `protobuf:"varint,1,opt,name=isTlsEnabled,proto3" json:"isTlsEnabled,omitempty"`
	IsMultiTls           bool     `protobuf:"varint,2,opt,name=isMultiTls,proto3" json:"isMultiTls,omitempty"`
	CertPath             string   `protobuf:"bytes,3,opt,name=cert_path,json=certPath,proto3" json:"cert_path,omitempty"`
	KeyPath              string   `protobuf:"bytes,4,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	PeerRootcertsPath    []string `protobuf:"bytes,5,rep,name=peer_rootcerts_path,json=peerRootcertsPath,proto3" json:"peer_rootcerts_path,omitempty"`
	ServerName           string   `protobuf:"bytes,6,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractTLSConfig) Reset()         { *m = ContractTLSConfig{} }
func (m *ContractTLSConfig) String() string { return proto.CompactTextString(m) }
func (*ContractTLSConfig) ProtoMessage()    {}
func (*ContractTLSConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{5}
}

func (m *ContractTLSConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractTLSConfig.Unmarshal(m, b)
}
func (m *ContractTLSConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractTLSConfig.Marshal(b, m, deterministic)
}
func (m *ContractTLSConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractTLSConfig.Merge(m, src)
}
func (m *ContractTLSConfig) XXX_Size() int {
	return xxx_messageInfo_ContractTLSConfig.Size(m)
}
func (m *ContractTLSConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractTLSConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ContractTLSConfig proto.InternalMessageInfo

func (m *ContractTLSConfig) GetIsTlsEnabled() bool {
	if m != nil {
		return m.IsTlsEnabled
	}
	return false
}

func (m *ContractTLSConfig) GetIsMultiTls() bool {
	if m != nil {
		return m.IsMultiTls
	}
	return false
}

func (m *ContractTLSConfig) GetCertPath() string {
	if m != nil {
		return m.CertPath
	}
	return ""
}

func (m *ContractTLSConfig) GetKeyPath() string {
	if m != nil {
		return m.KeyPath
	}
	return ""
}

func (m *ContractTLSConfig) GetPeerRootcertsPath() []string {
	if m != nil {
		return m.PeerRootcertsPath
	}
	return nil
}

func (m *ContractTLSConfig) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

type ContractMsg struct {
	Type ContractMsg_Type `protobuf:"varint,1,opt,name=type,proto3,enum=contract.ContractMsg_Type" json:"type,omitempty"`
	// Explanation for payload:
	// when wonde call smartcontract req:ContractInvocation
	// when wonde call smartcontract response:InvocationResponse
	// when smartcontract call wnode req:GetState or PutState or DelState or GetStateByRange
	// when smartcontract call wnode response: GetState:bytes PutState:nothing DelState:nothing GetStateByRange:QueryResponse
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Txid                 string   `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	Contractid           string   `protobuf:"bytes,4,opt,name=contractid,proto3" json:"contractid,omitempty"`
	Chainid              string   `protobuf:"bytes,5,opt,name=chainid,proto3" json:"chainid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractMsg) Reset()         { *m = ContractMsg{} }
func (m *ContractMsg) String() string { return proto.CompactTextString(m) }
func (*ContractMsg) ProtoMessage()    {}
func (*ContractMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{6}
}

func (m *ContractMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractMsg.Unmarshal(m, b)
}
func (m *ContractMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractMsg.Marshal(b, m, deterministic)
}
func (m *ContractMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractMsg.Merge(m, src)
}
func (m *ContractMsg) XXX_Size() int {
	return xxx_messageInfo_ContractMsg.Size(m)
}
func (m *ContractMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ContractMsg proto.InternalMessageInfo

func (m *ContractMsg) GetType() ContractMsg_Type {
	if m != nil {
		return m.Type
	}
	return ContractMsg_UNDEFINED
}

func (m *ContractMsg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ContractMsg) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *ContractMsg) GetContractid() string {
	if m != nil {
		return m.Contractid
	}
	return ""
}

func (m *ContractMsg) GetChainid() string {
	if m != nil {
		return m.Chainid
	}
	return ""
}

type GetState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetState) Reset()         { *m = GetState{} }
func (m *GetState) String() string { return proto.CompactTextString(m) }
func (*GetState) ProtoMessage()    {}
func (*GetState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{7}
}

func (m *GetState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetState.Unmarshal(m, b)
}
func (m *GetState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetState.Marshal(b, m, deterministic)
}
func (m *GetState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetState.Merge(m, src)
}
func (m *GetState) XXX_Size() int {
	return xxx_messageInfo_GetState.Size(m)
}
func (m *GetState) XXX_DiscardUnknown() {
	xxx_messageInfo_GetState.DiscardUnknown(m)
}

var xxx_messageInfo_GetState proto.InternalMessageInfo

func (m *GetState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type PutState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutState) Reset()         { *m = PutState{} }
func (m *PutState) String() string { return proto.CompactTextString(m) }
func (*PutState) ProtoMessage()    {}
func (*PutState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{8}
}

func (m *PutState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutState.Unmarshal(m, b)
}
func (m *PutState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutState.Marshal(b, m, deterministic)
}
func (m *PutState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutState.Merge(m, src)
}
func (m *PutState) XXX_Size() int {
	return xxx_messageInfo_PutState.Size(m)
}
func (m *PutState) XXX_DiscardUnknown() {
	xxx_messageInfo_PutState.DiscardUnknown(m)
}

var xxx_messageInfo_PutState proto.InternalMessageInfo

func (m *PutState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutState) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DelState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelState) Reset()         { *m = DelState{} }
func (m *DelState) String() string { return proto.CompactTextString(m) }
func (*DelState) ProtoMessage()    {}
func (*DelState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{9}
}

func (m *DelState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelState.Unmarshal(m, b)
}
func (m *DelState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelState.Marshal(b, m, deterministic)
}
func (m *DelState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelState.Merge(m, src)
}
func (m *DelState) XXX_Size() int {
	return xxx_messageInfo_DelState.Size(m)
}
func (m *DelState) XXX_DiscardUnknown() {
	xxx_messageInfo_DelState.DiscardUnknown(m)
}

var xxx_messageInfo_DelState proto.InternalMessageInfo

func (m *DelState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetStateByRange struct {
	BeginKey             string   `protobuf:"bytes,1,opt,name=beginKey,proto3" json:"beginKey,omitempty"`
	EndKey               string   `protobuf:"bytes,2,opt,name=endKey,proto3" json:"endKey,omitempty"`
	BufferSize           uint32   `protobuf:"varint,3,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	QueryId              string   `protobuf:"bytes,5,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateByRange) Reset()         { *m = GetStateByRange{} }
func (m *GetStateByRange) String() string { return proto.CompactTextString(m) }
func (*GetStateByRange) ProtoMessage()    {}
func (*GetStateByRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{10}
}

func (m *GetStateByRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateByRange.Unmarshal(m, b)
}
func (m *GetStateByRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateByRange.Marshal(b, m, deterministic)
}
func (m *GetStateByRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateByRange.Merge(m, src)
}
func (m *GetStateByRange) XXX_Size() int {
	return xxx_messageInfo_GetStateByRange.Size(m)
}
func (m *GetStateByRange) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateByRange.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateByRange proto.InternalMessageInfo

func (m *GetStateByRange) GetBeginKey() string {
	if m != nil {
		return m.BeginKey
	}
	return ""
}

func (m *GetStateByRange) GetEndKey() string {
	if m != nil {
		return m.EndKey
	}
	return ""
}

func (m *GetStateByRange) GetBufferSize() uint32 {
	if m != nil {
		return m.BufferSize
	}
	return 0
}

func (m *GetStateByRange) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

type GetHistoryForKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	BufferSize           uint32   `protobuf:"varint,2,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	QueryId              string   `protobuf:"bytes,3,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoryForKey) Reset()         { *m = GetHistoryForKey{} }
func (m *GetHistoryForKey) String() string { return proto.CompactTextString(m) }
func (*GetHistoryForKey) ProtoMessage()    {}
func (*GetHistoryForKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{11}
}

func (m *GetHistoryForKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryForKey.Unmarshal(m, b)
}
func (m *GetHistoryForKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryForKey.Marshal(b, m, deterministic)
}
func (m *GetHistoryForKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryForKey.Merge(m, src)
}
func (m *GetHistoryForKey) XXX_Size() int {
	return xxx_messageInfo_GetHistoryForKey.Size(m)
}
func (m *GetHistoryForKey) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryForKey.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryForKey proto.InternalMessageInfo

func (m *GetHistoryForKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetHistoryForKey) GetBufferSize() uint32 {
	if m != nil {
		return m.BufferSize
	}
	return 0
}

func (m *GetHistoryForKey) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

type HistoryForKey struct {
	HistoryArray         []*common.KeyModification `protobuf:"bytes,1,rep,name=history_array,json=historyArray,proto3" json:"history_array,omitempty"`
	IsOver               bool                      `protobuf:"varint,2,opt,name=isOver,proto3" json:"isOver,omitempty"`
	QueryId              string                    `protobuf:"bytes,3,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *HistoryForKey) Reset()         { *m = HistoryForKey{} }
func (m *HistoryForKey) String() string { return proto.CompactTextString(m) }
func (*HistoryForKey) ProtoMessage()    {}
func (*HistoryForKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{12}
}

func (m *HistoryForKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryForKey.Unmarshal(m, b)
}
func (m *HistoryForKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryForKey.Marshal(b, m, deterministic)
}
func (m *HistoryForKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryForKey.Merge(m, src)
}
func (m *HistoryForKey) XXX_Size() int {
	return xxx_messageInfo_HistoryForKey.Size(m)
}
func (m *HistoryForKey) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryForKey.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryForKey proto.InternalMessageInfo

func (m *HistoryForKey) GetHistoryArray() []*common.KeyModification {
	if m != nil {
		return m.HistoryArray
	}
	return nil
}

func (m *HistoryForKey) GetIsOver() bool {
	if m != nil {
		return m.IsOver
	}
	return false
}

func (m *HistoryForKey) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

type QueryResponse struct {
	KvArray              []*KVInfo `protobuf:"bytes,1,rep,name=kv_array,json=kvArray,proto3" json:"kv_array,omitempty"`
	IsOver               bool      `protobuf:"varint,2,opt,name=isOver,proto3" json:"isOver,omitempty"`
	QueryId              string    `protobuf:"bytes,3,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{13}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetKvArray() []*KVInfo {
	if m != nil {
		return m.KvArray
	}
	return nil
}

func (m *QueryResponse) GetIsOver() bool {
	if m != nil {
		return m.IsOver
	}
	return false
}

func (m *QueryResponse) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

type KVInfo struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVInfo) Reset()         { *m = KVInfo{} }
func (m *KVInfo) String() string { return proto.CompactTextString(m) }
func (*KVInfo) ProtoMessage()    {}
func (*KVInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{14}
}

func (m *KVInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVInfo.Unmarshal(m, b)
}
func (m *KVInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVInfo.Marshal(b, m, deterministic)
}
func (m *KVInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVInfo.Merge(m, src)
}
func (m *KVInfo) XXX_Size() int {
	return xxx_messageInfo_KVInfo.Size(m)
}
func (m *KVInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KVInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KVInfo proto.InternalMessageInfo

func (m *KVInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVInfo) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SqlQuery struct {
	Query                string                  `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Args                 *common.PrimitiveValues `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	BufferSize           uint32                  `protobuf:"varint,3,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	QId                  string                  `protobuf:"bytes,4,opt,name=q_id,json=qId,proto3" json:"q_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SqlQuery) Reset()         { *m = SqlQuery{} }
func (m *SqlQuery) String() string { return proto.CompactTextString(m) }
func (*SqlQuery) ProtoMessage()    {}
func (*SqlQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{15}
}

func (m *SqlQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlQuery.Unmarshal(m, b)
}
func (m *SqlQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlQuery.Marshal(b, m, deterministic)
}
func (m *SqlQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlQuery.Merge(m, src)
}
func (m *SqlQuery) XXX_Size() int {
	return xxx_messageInfo_SqlQuery.Size(m)
}
func (m *SqlQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SqlQuery proto.InternalMessageInfo

func (m *SqlQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SqlQuery) GetArgs() *common.PrimitiveValues {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *SqlQuery) GetBufferSize() uint32 {
	if m != nil {
		return m.BufferSize
	}
	return 0
}

func (m *SqlQuery) GetQId() string {
	if m != nil {
		return m.QId
	}
	return ""
}

type SqlExec struct {
	Query                string                  `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Args                 *common.PrimitiveValues `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SqlExec) Reset()         { *m = SqlExec{} }
func (m *SqlExec) String() string { return proto.CompactTextString(m) }
func (*SqlExec) ProtoMessage()    {}
func (*SqlExec) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{16}
}

func (m *SqlExec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlExec.Unmarshal(m, b)
}
func (m *SqlExec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlExec.Marshal(b, m, deterministic)
}
func (m *SqlExec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlExec.Merge(m, src)
}
func (m *SqlExec) XXX_Size() int {
	return xxx_messageInfo_SqlExec.Size(m)
}
func (m *SqlExec) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlExec.DiscardUnknown(m)
}

var xxx_messageInfo_SqlExec proto.InternalMessageInfo

func (m *SqlExec) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SqlExec) GetArgs() *common.PrimitiveValues {
	if m != nil {
		return m.Args
	}
	return nil
}

type SqlQueryResponse struct {
	RowsArray            []*common.PrimitiveValues `protobuf:"bytes,1,rep,name=rows_array,json=rowsArray,proto3" json:"rows_array,omitempty"`
	IsOver               bool                      `protobuf:"varint,2,opt,name=isOver,proto3" json:"isOver,omitempty"`
	QueryId              string                    `protobuf:"bytes,3,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SqlQueryResponse) Reset()         { *m = SqlQueryResponse{} }
func (m *SqlQueryResponse) String() string { return proto.CompactTextString(m) }
func (*SqlQueryResponse) ProtoMessage()    {}
func (*SqlQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ed56110ac5207b, []int{17}
}

func (m *SqlQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlQueryResponse.Unmarshal(m, b)
}
func (m *SqlQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlQueryResponse.Marshal(b, m, deterministic)
}
func (m *SqlQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlQueryResponse.Merge(m, src)
}
func (m *SqlQueryResponse) XXX_Size() int {
	return xxx_messageInfo_SqlQueryResponse.Size(m)
}
func (m *SqlQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SqlQueryResponse proto.InternalMessageInfo

func (m *SqlQueryResponse) GetRowsArray() []*common.PrimitiveValues {
	if m != nil {
		return m.RowsArray
	}
	return nil
}

func (m *SqlQueryResponse) GetIsOver() bool {
	if m != nil {
		return m.IsOver
	}
	return false
}

func (m *SqlQueryResponse) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

func init() {
	proto.RegisterEnum("contract.ContractMsg_Type", ContractMsg_Type_name, ContractMsg_Type_value)
	proto.RegisterType((*ContractDefinition)(nil), "contract.ContractDefinition")
	proto.RegisterMapType((map[string][]byte)(nil), "contract.ContractDefinition.ValidatorExtensionsEntry")
	proto.RegisterType((*DockerImageInfo)(nil), "contract.DockerImageInfo")
	proto.RegisterType((*ExternalContractInfo)(nil), "contract.ExternalContractInfo")
	proto.RegisterMapType((map[string]string)(nil), "contract.ExternalContractInfo.ExtensionsEntry")
	proto.RegisterType((*ContractConfig)(nil), "contract.ContractConfig")
	proto.RegisterType((*ContractGRPCConfig)(nil), "contract.ContractGRPCConfig")
	proto.RegisterType((*ContractTLSConfig)(nil), "contract.ContractTLSConfig")
	proto.RegisterType((*ContractMsg)(nil), "contract.ContractMsg")
	proto.RegisterType((*GetState)(nil), "contract.GetState")
	proto.RegisterType((*PutState)(nil), "contract.PutState")
	proto.RegisterType((*DelState)(nil), "contract.DelState")
	proto.RegisterType((*GetStateByRange)(nil), "contract.GetStateByRange")
	proto.RegisterType((*GetHistoryForKey)(nil), "contract.GetHistoryForKey")
	proto.RegisterType((*HistoryForKey)(nil), "contract.HistoryForKey")
	proto.RegisterType((*QueryResponse)(nil), "contract.QueryResponse")
	proto.RegisterType((*KVInfo)(nil), "contract.KVInfo")
	proto.RegisterType((*SqlQuery)(nil), "contract.SqlQuery")
	proto.RegisterType((*SqlExec)(nil), "contract.SqlExec")
	proto.RegisterType((*SqlQueryResponse)(nil), "contract.SqlQueryResponse")
}

func init() {
	proto.RegisterFile("contract/contract.proto", fileDescriptor_d5ed56110ac5207b)
}

var fileDescriptor_d5ed56110ac5207b = []byte{
	// 1323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xdb, 0x46,
	0x16, 0x8e, 0x7e, 0x6c, 0x53, 0x47, 0x92, 0x2d, 0x8f, 0xb3, 0x1b, 0xad, 0x12, 0xec, 0x3a, 0x5c,
	0x04, 0x35, 0x10, 0x54, 0x0e, 0x5c, 0xf4, 0x07, 0x41, 0x72, 0x91, 0x58, 0xb2, 0x23, 0xd8, 0x96,
	0x1d, 0x4a, 0x31, 0xea, 0xde, 0x30, 0x23, 0xf2, 0x58, 0x1a, 0x98, 0xe2, 0x50, 0x33, 0x23, 0xc5,
	0x0a, 0x50, 0xa0, 0x79, 0x93, 0x3e, 0x46, 0x2f, 0xfa, 0x30, 0x79, 0x90, 0x5e, 0x14, 0x33, 0x24,
	0x65, 0x39, 0x72, 0xd2, 0x34, 0xe8, 0xdd, 0x39, 0xdf, 0xf9, 0x9d, 0xf3, 0x47, 0xc2, 0x1d, 0x8f,
	0x87, 0x4a, 0x50, 0x4f, 0x6d, 0xa7, 0x44, 0x3d, 0x12, 0x5c, 0x71, 0x62, 0xa5, 0x7c, 0x6d, 0xc3,
	0xe3, 0xc3, 0x21, 0x0f, 0xb7, 0x03, 0xf4, 0xfb, 0x28, 0x62, 0x71, 0xad, 0x9a, 0x80, 0x4a, 0xd0,
	0x50, 0x52, 0x4f, 0x31, 0x1e, 0xc6, 0x12, 0xfb, 0x8f, 0x1c, 0x90, 0xdd, 0xc4, 0xb6, 0x81, 0xe7,
	0x2c, 0x64, 0x5a, 0x48, 0xfe, 0x0f, 0xe5, 0xd4, 0xa3, 0x1b, 0xd2, 0x21, 0x56, 0x33, 0x9b, 0x99,
	0xad, 0x82, 0x53, 0x4a, 0xc1, 0x36, 0x1d, 0x22, 0x79, 0x00, 0xab, 0xd2, 0x1b, 0xe0, 0x90, 0xba,
	0x13, 0x14, 0x92, 0xf1, 0xb0, 0x9a, 0x35, 0x5a, 0xe5, 0x18, 0x3d, 0x8d, 0x41, 0xf2, 0x15, 0xac,
	0x49, 0x1c, 0x8d, 0x31, 0xf4, 0xd0, 0x0d, 0xc7, 0xc3, 0x1e, 0x8a, 0x6a, 0x6e, 0x33, 0xb3, 0x55,
	0x76, 0x56, 0x53, 0xb8, 0x6d, 0x50, 0xb2, 0x09, 0x45, 0x1f, 0xa5, 0x27, 0x58, 0xa4, 0x73, 0xa8,
	0xe6, 0x8d, 0xb3, 0x79, 0x88, 0xdc, 0x87, 0x92, 0xc0, 0xd1, 0x98, 0x09, 0x74, 0x75, 0xa6, 0xd5,
	0xa5, 0xcd, 0xcc, 0x96, 0xe5, 0x14, 0x13, 0xac, 0x15, 0x32, 0x45, 0x6c, 0x28, 0xcb, 0x51, 0xe0,
	0xfa, 0x3d, 0x37, 0xce, 0xa2, 0xba, 0x1c, 0xbb, 0x91, 0xa3, 0xa0, 0xd1, 0xeb, 0x18, 0x48, 0x67,
	0x34, 0x60, 0x52, 0x71, 0x31, 0x75, 0xe5, 0x38, 0x8a, 0xb8, 0x50, 0xd5, 0x15, 0xe3, 0x69, 0x35,
	0x81, 0x3b, 0x31, 0x4a, 0xbe, 0x06, 0x42, 0xa3, 0x48, 0xf0, 0x09, 0x0d, 0xdc, 0x09, 0x0d, 0x98,
	0x4f, 0x15, 0x17, 0x55, 0x30, 0x1e, 0xd7, 0x53, 0xc9, 0x69, 0x2a, 0x20, 0x03, 0xb8, 0x3d, 0xd3,
	0x72, 0xf1, 0x52, 0x61, 0xa8, 0x0b, 0x20, 0xab, 0xc5, 0xcd, 0xdc, 0x56, 0x71, 0xe7, 0xdb, 0xfa,
	0xac, 0x69, 0x8b, 0x15, 0xaf, 0xcf, 0xbc, 0x34, 0x67, 0x76, 0xcd, 0x50, 0x89, 0xa9, 0xb3, 0x31,
	0x59, 0x94, 0xd4, 0xf6, 0xa0, 0xfa, 0x31, 0x03, 0x52, 0x81, 0xdc, 0x05, 0x4e, 0x93, 0x8e, 0x69,
	0x92, 0xdc, 0x86, 0xa5, 0x09, 0x0d, 0xc6, 0x68, 0xfa, 0x53, 0x72, 0x62, 0xe6, 0x71, 0xf6, 0x87,
	0x8c, 0xfd, 0x04, 0xd6, 0x1a, 0xdc, 0xbb, 0x40, 0xd1, 0x1a, 0xd2, 0x3e, 0xb6, 0xc2, 0x73, 0x4e,
	0x56, 0x21, 0xdb, 0x6a, 0x24, 0xd6, 0xd9, 0x56, 0x83, 0xfc, 0x07, 0x2c, 0x81, 0x11, 0x77, 0x15,
	0xed, 0x27, 0xfd, 0x5d, 0xd1, 0x7c, 0x97, 0xf6, 0xed, 0x5f, 0xb3, 0x70, 0x5b, 0x47, 0x17, 0x21,
	0x0d, 0xd2, 0x27, 0x19, 0x1f, 0xf7, 0xa1, 0x24, 0x69, 0xe8, 0xf7, 0xf8, 0xa5, 0xab, 0xa6, 0x51,
	0x3a, 0x3d, 0xc5, 0x04, 0xeb, 0x4e, 0xa3, 0xcf, 0x1e, 0x1e, 0x02, 0x79, 0x8f, 0xfb, 0x68, 0x26,
	0xa6, 0xe4, 0x18, 0x9a, 0xdc, 0x85, 0x42, 0x84, 0x28, 0x5c, 0x0f, 0x85, 0x32, 0x53, 0x52, 0x72,
	0x2c, 0x0d, 0xec, 0xa2, 0x50, 0xa4, 0x0d, 0x30, 0x57, 0xf9, 0x25, 0x53, 0xf9, 0xfa, 0x55, 0xe5,
	0x6f, 0x4a, 0xb7, 0xfe, 0x61, 0xc9, 0xe7, 0x3c, 0xd4, 0x9e, 0xc2, 0xda, 0xdf, 0x2c, 0x70, 0x61,
	0xbe, 0xc0, 0xbf, 0x67, 0x60, 0x35, 0x8d, 0xb5, 0xcb, 0xc3, 0x73, 0xd6, 0x27, 0x8f, 0x01, 0x54,
	0x20, 0x5d, 0xcf, 0x70, 0xc6, 0x4b, 0x71, 0xe7, 0xee, 0xe2, 0x6c, 0x74, 0x0f, 0x3b, 0xb1, 0x81,
	0x53, 0x50, 0x81, 0x4c, 0x6c, 0x9f, 0x42, 0xb1, 0x2f, 0x22, 0x2f, 0x35, 0xce, 0x1a, 0xe3, 0x7b,
	0x8b, 0xc6, 0xfb, 0xce, 0xc9, 0x6e, 0x62, 0x0d, 0xda, 0x20, 0x31, 0x27, 0x90, 0x37, 0xd3, 0x9e,
	0x33, 0x69, 0x1a, 0x5a, 0x57, 0x33, 0xe0, 0x7d, 0x37, 0xc0, 0x09, 0x06, 0xc9, 0xce, 0x59, 0x01,
	0xef, 0x1f, 0x6a, 0xde, 0x0e, 0xae, 0xae, 0xc3, 0x95, 0x4b, 0x52, 0x03, 0x8b, 0x85, 0x0a, 0xc5,
	0x84, 0x06, 0x26, 0xff, 0xb2, 0x33, 0xe3, 0x49, 0x15, 0x56, 0x14, 0x1b, 0x22, 0x1f, 0x2b, 0x93,
	0x5d, 0xd9, 0x49, 0x59, 0xbd, 0xde, 0x43, 0x16, 0xb6, 0x52, 0xc3, 0xf8, 0x06, 0xcc, 0x43, 0xf6,
	0xfb, 0x0c, 0xac, 0x2f, 0x3c, 0x9f, 0xd8, 0x50, 0x62, 0xb2, 0x1b, 0xc8, 0x66, 0x48, 0x7b, 0x01,
	0xfa, 0x26, 0xa2, 0xe5, 0x5c, 0xc3, 0xc8, 0x7f, 0x01, 0x98, 0x3c, 0x1a, 0x07, 0x8a, 0x75, 0x03,
	0x69, 0x02, 0x5b, 0xce, 0x1c, 0xa2, 0x1f, 0xa9, 0xa7, 0xc5, 0x8d, 0xa8, 0x1a, 0x24, 0xaf, 0xb7,
	0x34, 0x70, 0x42, 0xd5, 0x40, 0x4f, 0xf8, 0x05, 0x4e, 0x63, 0x59, 0x5c, 0x80, 0x95, 0x0b, 0x9c,
	0x1a, 0x51, 0x1d, 0x36, 0xcc, 0xa8, 0x09, 0xce, 0x95, 0xd6, 0x97, 0xb1, 0x96, 0x1e, 0xab, 0x82,
	0xb3, 0xae, 0x45, 0x4e, 0x2a, 0x31, 0xfa, 0xff, 0x83, 0xa2, 0x44, 0x31, 0x41, 0x11, 0x5f, 0xcd,
	0xf8, 0xf6, 0x40, 0x0c, 0xe9, 0x9b, 0x69, 0xbf, 0xcf, 0x42, 0x31, 0x7d, 0xe2, 0x91, 0xec, 0x93,
	0x3a, 0xe4, 0x67, 0x1b, 0xb2, 0xba, 0x53, 0x5b, 0xec, 0xe4, 0x91, 0xec, 0xd7, 0xf5, 0xc2, 0x38,
	0x46, 0x4f, 0x97, 0x37, 0xa2, 0xd3, 0x80, 0x53, 0x3f, 0x59, 0xe6, 0x94, 0xd5, 0xbd, 0x55, 0x97,
	0xcc, 0x4f, 0x7b, 0xab, 0x69, 0x5d, 0x96, 0xd4, 0x21, 0xf3, 0x93, 0xb7, 0xcd, 0x21, 0xda, 0x9b,
	0x37, 0xa0, 0x2c, 0x64, 0xbe, 0x39, 0xa5, 0x05, 0x27, 0x65, 0xed, 0xdf, 0x32, 0x90, 0x37, 0x7b,
	0x5a, 0x86, 0xc2, 0xab, 0x76, 0xa3, 0xb9, 0xd7, 0x6a, 0x37, 0x1b, 0x95, 0x5b, 0xc4, 0x82, 0x7c,
	0xab, 0xdd, 0xea, 0x56, 0x32, 0x04, 0x60, 0xb9, 0xd5, 0x3e, 0x3d, 0x3e, 0x68, 0x56, 0xb2, 0x9a,
	0xde, 0x6f, 0x76, 0xdd, 0x83, 0xd3, 0x4a, 0x4e, 0xd3, 0x27, 0xaf, 0x0c, 0x9d, 0xd7, 0x74, 0xa3,
	0x79, 0xa8, 0xe9, 0x25, 0xb2, 0x01, 0x6b, 0xb1, 0x8e, 0xfb, 0xfc, 0xcc, 0x75, 0x9e, 0xb5, 0xf7,
	0x9b, 0x95, 0x65, 0x72, 0x07, 0x36, 0x34, 0xf8, 0xa2, 0xd5, 0xe9, 0x1e, 0x3b, 0x67, 0xee, 0xde,
	0xb1, 0xe3, 0x1e, 0x34, 0xcf, 0x2a, 0x2b, 0xa4, 0x04, 0x56, 0xe7, 0xe5, 0xa1, 0x6b, 0x62, 0x59,
	0x64, 0x15, 0x20, 0xe6, 0x4c, 0xbc, 0x42, 0x2a, 0x6d, 0xfe, 0xd8, 0xdc, 0xad, 0x80, 0x4e, 0x51,
	0x73, 0x2f, 0x5f, 0x35, 0x9d, 0xb3, 0x4a, 0xd1, 0xbe, 0x07, 0xd6, 0x3e, 0xaa, 0x8e, 0xa2, 0x0a,
	0x17, 0x57, 0xd5, 0xde, 0x01, 0xeb, 0x64, 0xfc, 0x31, 0xe9, 0xcd, 0x97, 0x52, 0x7b, 0x6c, 0x60,
	0xf0, 0x31, 0x8f, 0xef, 0x32, 0xb0, 0x96, 0x06, 0x7c, 0x3e, 0x75, 0x68, 0xd8, 0x47, 0xbd, 0x21,
	0x3d, 0xec, 0xb3, 0xf0, 0x60, 0xa6, 0x3a, 0xe3, 0xc9, 0xbf, 0x61, 0x19, 0x43, 0x5f, 0x4b, 0xe2,
	0x6b, 0x91, 0x70, 0x7a, 0x76, 0x7a, 0xe3, 0xf3, 0x73, 0x14, 0xae, 0x64, 0x6f, 0x31, 0xd9, 0x0f,
	0x88, 0xa1, 0x0e, 0x7b, 0x8b, 0x7a, 0x4e, 0x47, 0x63, 0x14, 0x53, 0xf7, 0xaa, 0x5d, 0x86, 0x6f,
	0xf9, 0xf6, 0x6b, 0xa8, 0xec, 0xa3, 0x7a, 0x11, 0x7f, 0xbd, 0xf6, 0xb8, 0xd0, 0xfe, 0x16, 0x5f,
	0xf7, 0x41, 0x84, 0xec, 0x27, 0x23, 0xe4, 0xae, 0x47, 0xf8, 0x25, 0x03, 0xe5, 0xeb, 0xfe, 0x9f,
	0x40, 0x39, 0xfd, 0x8a, 0x52, 0x21, 0xa8, 0x8e, 0xa4, 0x8f, 0xed, 0x9d, 0x7a, 0xfc, 0xb3, 0x51,
	0x3f, 0xc0, 0xe9, 0x11, 0xf7, 0xd9, 0x39, 0xf3, 0xa8, 0xfe, 0xc2, 0x39, 0xa5, 0x44, 0xfb, 0x99,
	0x56, 0xd6, 0x55, 0x60, 0xf2, 0x78, 0x82, 0x22, 0xd9, 0xd6, 0x84, 0xfb, 0x54, 0x0a, 0x1c, 0xca,
	0x2f, 0x35, 0xe9, 0xa0, 0x8c, 0x78, 0x28, 0x91, 0x3c, 0x04, 0xeb, 0x62, 0x72, 0x2d, 0x78, 0xe5,
	0x6a, 0x81, 0x0e, 0x4e, 0xf5, 0x6d, 0x77, 0x56, 0x2e, 0x26, 0x5f, 0x1c, 0xf0, 0x11, 0x2c, 0xc7,
	0x5e, 0x3e, 0x7b, 0x52, 0xde, 0x65, 0xc0, 0xea, 0x8c, 0x02, 0x93, 0xa6, 0x56, 0x31, 0x9e, 0x12,
	0xb3, 0x98, 0x21, 0x0f, 0x21, 0x4f, 0x45, 0x5f, 0x26, 0xb7, 0x7b, 0x56, 0xad, 0x13, 0xc1, 0x86,
	0x4c, 0xb1, 0x09, 0x9e, 0x6a, 0x47, 0xd2, 0x31, 0x4a, 0x7f, 0x3d, 0x13, 0xeb, 0x90, 0x1f, 0xb9,
	0xb3, 0xdd, 0xce, 0x8d, 0x5a, 0xbe, 0x7d, 0x08, 0x2b, 0x9d, 0x51, 0xd0, 0xbc, 0x44, 0xef, 0x1f,
	0xc8, 0xc0, 0xfe, 0x19, 0x2a, 0xe9, 0x83, 0x66, 0x75, 0xff, 0x0e, 0x40, 0xf0, 0x37, 0xf2, 0xe6,
	0xb6, 0x7f, 0xe8, 0xa6, 0xa0, 0x55, 0xbf, 0xb4, 0x05, 0x3b, 0x2f, 0xc0, 0xea, 0x1c, 0xed, 0xd2,
	0x20, 0x40, 0x41, 0x9e, 0xc0, 0xb2, 0xa6, 0x3a, 0x47, 0xe4, 0x5f, 0x37, 0xde, 0xc9, 0xda, 0xcd,
	0xb0, 0x7d, 0x6b, 0x2b, 0xf3, 0x28, 0xf3, 0xfc, 0x35, 0x3c, 0xf0, 0xf8, 0xb0, 0x3e, 0x18, 0xd3,
	0x37, 0xc8, 0xea, 0x6f, 0x18, 0x86, 0x28, 0xcc, 0xb5, 0x8b, 0xff, 0x84, 0x67, 0xa6, 0x3f, 0x7d,
	0xdf, 0x67, 0x2a, 0x55, 0xf3, 0xf8, 0x70, 0x3b, 0xe2, 0x4c, 0x4a, 0xfd, 0x6e, 0x2a, 0xbc, 0xc1,
	0xf6, 0x9c, 0xe1, 0xb6, 0x31, 0x9c, 0xfd, 0x8a, 0xf7, 0x96, 0x0d, 0xff, 0xcd, 0x9f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x00, 0x55, 0xf7, 0x49, 0xa6, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SMCallerClient is the client API for SMCaller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SMCallerClient interface {
	CallSM(ctx context.Context, opts ...grpc.CallOption) (SMCaller_CallSMClient, error)
}

type sMCallerClient struct {
	cc grpc.ClientConnInterface
}

func NewSMCallerClient(cc grpc.ClientConnInterface) SMCallerClient {
	return &sMCallerClient{cc}
}

func (c *sMCallerClient) CallSM(ctx context.Context, opts ...grpc.CallOption) (SMCaller_CallSMClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SMCaller_serviceDesc.Streams[0], "/contract.SMCaller/CallSM", opts...)
	if err != nil {
		return nil, err
	}
	x := &sMCallerCallSMClient{stream}
	return x, nil
}

type SMCaller_CallSMClient interface {
	Send(*ContractMsg) error
	Recv() (*ContractMsg, error)
	grpc.ClientStream
}

type sMCallerCallSMClient struct {
	grpc.ClientStream
}

func (x *sMCallerCallSMClient) Send(m *ContractMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sMCallerCallSMClient) Recv() (*ContractMsg, error) {
	m := new(ContractMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SMCallerServer is the server API for SMCaller service.
type SMCallerServer interface {
	CallSM(SMCaller_CallSMServer) error
}

// UnimplementedSMCallerServer can be embedded to have forward compatible implementations.
type UnimplementedSMCallerServer struct {
}

func (*UnimplementedSMCallerServer) CallSM(srv SMCaller_CallSMServer) error {
	return status.Errorf(codes.Unimplemented, "method CallSM not implemented")
}

func RegisterSMCallerServer(s *grpc.Server, srv SMCallerServer) {
	s.RegisterService(&_SMCaller_serviceDesc, srv)
}

func _SMCaller_CallSM_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SMCallerServer).CallSM(&sMCallerCallSMServer{stream})
}

type SMCaller_CallSMServer interface {
	Send(*ContractMsg) error
	Recv() (*ContractMsg, error)
	grpc.ServerStream
}

type sMCallerCallSMServer struct {
	grpc.ServerStream
}

func (x *sMCallerCallSMServer) Send(m *ContractMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sMCallerCallSMServer) Recv() (*ContractMsg, error) {
	m := new(ContractMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SMCaller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contract.SMCaller",
	HandlerType: (*SMCallerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CallSM",
			Handler:       _SMCaller_CallSM_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "contract/contract.proto",
}
